/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: d181146f5059766627aeaf077cf75eae)
interface __BaseEnv_Env {
	SHARE_BUCKET: R2Bucket;
	SHARE_RATE_LIMITER: RateLimit;
	CONTACT_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
