import type { EmblemCatalogAsset } from './types';

export const LEGACY_EMBLEM_CATALOG_ASSETS: readonly EmblemCatalogAsset[] = [
  {
    id: 'body-circle',
    category: 'body',
    publicPath: '/emblem-creator/original/body-circle.svg',
    width: 100,
    height: 100,
    name: { en: 'Circle', zh: '圆形' },
  },
  {
    id: 'body-square',
    category: 'body',
    publicPath: '/emblem-creator/original/body-square.svg',
    width: 100,
    height: 100,
    name: { en: 'Square', zh: '方形' },
  },
  {
    id: 'body-diamond',
    category: 'body',
    publicPath: '/emblem-creator/original/body-diamond.svg',
    width: 100,
    height: 100,
    name: { en: 'Diamond', zh: '菱形' },
  },
  {
    id: 'body-triangle',
    category: 'body',
    publicPath: '/emblem-creator/original/body-triangle.svg',
    width: 100,
    height: 100,
    name: { en: 'Triangle', zh: '三角形' },
  },
  {
    id: 'body-shield',
    category: 'body',
    publicPath: '/emblem-creator/original/body-shield.svg',
    width: 100,
    height: 100,
    name: { en: 'Shield', zh: '盾形' },
  },
  {
    id: 'body-hexagon',
    category: 'body',
    publicPath: '/emblem-creator/original/body-hexagon.svg',
    width: 100,
    height: 100,
    name: { en: 'Hexagon', zh: '六边形' },
  },
  {
    id: 'detail-ring',
    category: 'detail',
    publicPath: '/emblem-creator/original/detail-ring.svg',
    width: 100,
    height: 100,
    name: { en: 'Ring', zh: '环圈' },
  },
  {
    id: 'detail-double-ring',
    category: 'detail',
    publicPath: '/emblem-creator/original/detail-double-ring.svg',
    width: 100,
    height: 100,
    name: { en: 'Double Ring', zh: '双环' },
  },
  {
    id: 'detail-diagonal-stripe',
    category: 'detail',
    publicPath: '/emblem-creator/original/detail-diagonal-stripe.svg',
    width: 100,
    height: 100,
    name: { en: 'Diagonal Stripe', zh: '斜纹' },
  },
  {
    id: 'detail-horizontal-bars',
    category: 'detail',
    publicPath: '/emblem-creator/original/detail-horizontal-bars.svg',
    width: 100,
    height: 100,
    name: { en: 'Horizontal Bars', zh: '横条' },
  },
  {
    id: 'detail-rays',
    category: 'detail',
    publicPath: '/emblem-creator/original/detail-rays.svg',
    width: 100,
    height: 100,
    name: { en: 'Rays', zh: '光芒' },
  },
  {
    id: 'detail-laurel',
    category: 'detail',
    publicPath: '/emblem-creator/original/detail-laurel.svg',
    width: 100,
    height: 100,
    name: { en: 'Laurel', zh: '月桂枝' },
  },
  {
    id: 'crest-star',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-star.svg',
    width: 100,
    height: 100,
    name: { en: 'Star', zh: '星形' },
  },
  {
    id: 'crest-moon',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-moon.svg',
    width: 100,
    height: 100,
    name: { en: 'Moon', zh: '月牙' },
  },
  {
    id: 'crest-sun',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-sun.svg',
    width: 100,
    height: 100,
    name: { en: 'Sun', zh: '太阳' },
  },
  {
    id: 'crest-sword',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-sword.svg',
    width: 100,
    height: 100,
    name: { en: 'Sword', zh: '宝剑' },
  },
  {
    id: 'crest-arrow',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-arrow.svg',
    width: 100,
    height: 100,
    name: { en: 'Arrow', zh: '箭矢' },
  },
  {
    id: 'crest-crown',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-crown.svg',
    width: 100,
    height: 100,
    name: { en: 'Crown', zh: '王冠' },
  },
  {
    id: 'crest-eye',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-eye.svg',
    width: 100,
    height: 100,
    name: { en: 'Eye', zh: '眼睛' },
  },
  {
    id: 'crest-lightning',
    category: 'crest',
    publicPath: '/emblem-creator/original/crest-lightning.svg',
    width: 100,
    height: 100,
    name: { en: 'Lightning', zh: '闪电' },
  },
];
