import type { EmblemCatalogAsset } from './types';

export const ROLLFORFANTASY_ASSETS: readonly EmblemCatalogAsset[] = [
  {
    id: 'rff-emblems-1',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems1.png',
    width: 261,
    height: 261,
    name: { en: 'Main body 1', zh: '主体 1' },
  },
  {
    id: 'rff-emblems-2',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems2.png',
    width: 261,
    height: 261,
    name: { en: 'Main body 2', zh: '主体 2' },
  },
  {
    id: 'rff-emblems-3',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems3.png',
    width: 259,
    height: 259,
    name: { en: 'Main body 3', zh: '主体 3' },
  },
  {
    id: 'rff-emblems-4',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems4.png',
    width: 261,
    height: 261,
    name: { en: 'Main body 4', zh: '主体 4' },
  },
  {
    id: 'rff-emblems-5',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems5.png',
    width: 255,
    height: 256,
    name: { en: 'Main body 5', zh: '主体 5' },
  },
  {
    id: 'rff-emblems-6',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems6.png',
    width: 259,
    height: 246,
    name: { en: 'Main body 6', zh: '主体 6' },
  },
  {
    id: 'rff-emblems-7',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems7.png',
    width: 263,
    height: 227,
    name: { en: 'Main body 7', zh: '主体 7' },
  },
  {
    id: 'rff-emblems-8',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems8.png',
    width: 259,
    height: 263,
    name: { en: 'Main body 8', zh: '主体 8' },
  },
  {
    id: 'rff-emblems-9',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems9.png',
    width: 259,
    height: 259,
    name: { en: 'Main body 9', zh: '主体 9' },
  },
  {
    id: 'rff-emblems-10',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems10.png',
    width: 255,
    height: 249,
    name: { en: 'Main body 10', zh: '主体 10' },
  },
  {
    id: 'rff-emblems-11',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems11.png',
    width: 257,
    height: 254,
    name: { en: 'Main body 11', zh: '主体 11' },
  },
  {
    id: 'rff-emblems-12',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems12.png',
    width: 259,
    height: 247,
    name: { en: 'Main body 12', zh: '主体 12' },
  },
  {
    id: 'rff-emblems-13',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems13.png',
    width: 259,
    height: 249,
    name: { en: 'Main body 13', zh: '主体 13' },
  },
  {
    id: 'rff-emblems-14',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems14.png',
    width: 261,
    height: 248,
    name: { en: 'Main body 14', zh: '主体 14' },
  },
  {
    id: 'rff-emblems-15',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems15.png',
    width: 261,
    height: 249,
    name: { en: 'Main body 15', zh: '主体 15' },
  },
  {
    id: 'rff-emblems-16',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems16.png',
    width: 135,
    height: 261,
    name: { en: 'Main body 16', zh: '主体 16' },
  },
  {
    id: 'rff-emblems-17',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems17.png',
    width: 259,
    height: 259,
    name: { en: 'Main body 17', zh: '主体 17' },
  },
  {
    id: 'rff-emblems-18',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems18.png',
    width: 135,
    height: 261,
    name: { en: 'Main body 18', zh: '主体 18' },
  },
  {
    id: 'rff-emblems-19',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems19.png',
    width: 257,
    height: 257,
    name: { en: 'Main body 19', zh: '主体 19' },
  },
  {
    id: 'rff-emblems-20',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems20.png',
    width: 135,
    height: 261,
    name: { en: 'Main body 20', zh: '主体 20' },
  },
  {
    id: 'rff-emblems-21',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems21.png',
    width: 261,
    height: 261,
    name: { en: 'Main body 21', zh: '主体 21' },
  },
  {
    id: 'rff-emblems-22',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems22.png',
    width: 135,
    height: 261,
    name: { en: 'Main body 22', zh: '主体 22' },
  },
  {
    id: 'rff-emblems-23',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems23.png',
    width: 261,
    height: 261,
    name: { en: 'Main body 23', zh: '主体 23' },
  },
  {
    id: 'rff-emblems-24',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems24.png',
    width: 135,
    height: 261,
    name: { en: 'Main body 24', zh: '主体 24' },
  },
  {
    id: 'rff-emblems-25',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems25.png',
    width: 135,
    height: 263,
    name: { en: 'Main body 25', zh: '主体 25' },
  },
  {
    id: 'rff-emblems-26',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems26.png',
    width: 137,
    height: 263,
    name: { en: 'Main body 26', zh: '主体 26' },
  },
  {
    id: 'rff-emblems-27',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems27.png',
    width: 136,
    height: 263,
    name: { en: 'Main body 27', zh: '主体 27' },
  },
  {
    id: 'rff-emblems-28',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems28.png',
    width: 135,
    height: 263,
    name: { en: 'Main body 28', zh: '主体 28' },
  },
  {
    id: 'rff-emblems-29',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems29.png',
    width: 133,
    height: 265,
    name: { en: 'Main body 29', zh: '主体 29' },
  },
  {
    id: 'rff-emblems-30',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems30.png',
    width: 265,
    height: 265,
    name: { en: 'Main body 30', zh: '主体 30' },
  },
  {
    id: 'rff-emblems-31',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems31.png',
    width: 265,
    height: 265,
    name: { en: 'Main body 31', zh: '主体 31' },
  },
  {
    id: 'rff-emblems-32',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems32.png',
    width: 259,
    height: 259,
    name: { en: 'Main body 32', zh: '主体 32' },
  },
  {
    id: 'rff-emblems-33',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems33.png',
    width: 233,
    height: 261,
    name: { en: 'Main body 33', zh: '主体 33' },
  },
  {
    id: 'rff-emblems-34',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems34.png',
    width: 233,
    height: 261,
    name: { en: 'Main body 34', zh: '主体 34' },
  },
  {
    id: 'rff-emblems-35',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems35.png',
    width: 223,
    height: 259,
    name: { en: 'Main body 35', zh: '主体 35' },
  },
  {
    id: 'rff-emblems-36',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems36.png',
    width: 262,
    height: 262,
    name: { en: 'Main body 36', zh: '主体 36' },
  },
  {
    id: 'rff-emblems-37',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems37.png',
    width: 231,
    height: 263,
    name: { en: 'Main body 37', zh: '主体 37' },
  },
  {
    id: 'rff-emblems-38',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems38.png',
    width: 227,
    height: 254,
    name: { en: 'Main body 38', zh: '主体 38' },
  },
  {
    id: 'rff-emblems-39',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems39.png',
    width: 227,
    height: 259,
    name: { en: 'Main body 39', zh: '主体 39' },
  },
  {
    id: 'rff-emblems-40',
    category: 'body',
    publicPath: '/emblem-creator/rollforfantasy/emblems40.png',
    width: 235,
    height: 263,
    name: { en: 'Main body 40', zh: '主体 40' },
  },
  {
    id: 'rff-detail-1',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail1.png',
    width: 263,
    height: 38,
    name: { en: 'Detail 1', zh: '细节 1' },
  },
  {
    id: 'rff-detail-2',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail2.png',
    width: 243,
    height: 21,
    name: { en: 'Detail 2', zh: '细节 2' },
  },
  {
    id: 'rff-detail-3',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail3.png',
    width: 255,
    height: 38,
    name: { en: 'Detail 3', zh: '细节 3' },
  },
  {
    id: 'rff-detail-4',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail4.png',
    width: 220,
    height: 148,
    name: { en: 'Detail 4', zh: '细节 4' },
  },
  {
    id: 'rff-detail-5',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail5.png',
    width: 221,
    height: 127,
    name: { en: 'Detail 5', zh: '细节 5' },
  },
  {
    id: 'rff-detail-6',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail6.png',
    width: 221,
    height: 179,
    name: { en: 'Detail 6', zh: '细节 6' },
  },
  {
    id: 'rff-detail-7',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail7.png',
    width: 221,
    height: 209,
    name: { en: 'Detail 7', zh: '细节 7' },
  },
  {
    id: 'rff-detail-8',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail8.png',
    width: 221,
    height: 261,
    name: { en: 'Detail 8', zh: '细节 8' },
  },
  {
    id: 'rff-detail-9',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail9.png',
    width: 221,
    height: 292,
    name: { en: 'Detail 9', zh: '细节 9' },
  },
  {
    id: 'rff-detail-10',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail10.png',
    width: 221,
    height: 325,
    name: { en: 'Detail 10', zh: '细节 10' },
  },
  {
    id: 'rff-detail-11',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail11.png',
    width: 221,
    height: 73,
    name: { en: 'Detail 11', zh: '细节 11' },
  },
  {
    id: 'rff-detail-12',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail12.png',
    width: 221,
    height: 109,
    name: { en: 'Detail 12', zh: '细节 12' },
  },
  {
    id: 'rff-detail-13',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail13.png',
    width: 87,
    height: 83,
    name: { en: 'Detail 13', zh: '细节 13' },
  },
  {
    id: 'rff-detail-14',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail14.png',
    width: 201,
    height: 83,
    name: { en: 'Detail 14', zh: '细节 14' },
  },
  {
    id: 'rff-detail-15',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail15.png',
    width: 221,
    height: 194,
    name: { en: 'Detail 15', zh: '细节 15' },
  },
  {
    id: 'rff-detail-16',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail16.png',
    width: 221,
    height: 231,
    name: { en: 'Detail 16', zh: '细节 16' },
  },
  {
    id: 'rff-detail-17',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail17.png',
    width: 221,
    height: 268,
    name: { en: 'Detail 17', zh: '细节 17' },
  },
  {
    id: 'rff-detail-18',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail18.png',
    width: 187,
    height: 180,
    name: { en: 'Detail 18', zh: '细节 18' },
  },
  {
    id: 'rff-detail-19',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail19.png',
    width: 263,
    height: 99,
    name: { en: 'Detail 19', zh: '细节 19' },
  },
  {
    id: 'rff-detail-20',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail20.png',
    width: 124,
    height: 262,
    name: { en: 'Detail 20', zh: '细节 20' },
  },
  {
    id: 'rff-detail-21',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail21.png',
    width: 90,
    height: 228,
    name: { en: 'Detail 21', zh: '细节 21' },
  },
  {
    id: 'rff-detail-22',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail22.png',
    width: 85,
    height: 195,
    name: { en: 'Detail 22', zh: '细节 22' },
  },
  {
    id: 'rff-detail-23',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail23.png',
    width: 208,
    height: 98,
    name: { en: 'Detail 23', zh: '细节 23' },
  },
  {
    id: 'rff-detail-24',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail24.png',
    width: 105,
    height: 218,
    name: { en: 'Detail 24', zh: '细节 24' },
  },
  {
    id: 'rff-detail-25',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail25.png',
    width: 72,
    height: 200,
    name: { en: 'Detail 25', zh: '细节 25' },
  },
  {
    id: 'rff-detail-26',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail26.png',
    width: 76,
    height: 222,
    name: { en: 'Detail 26', zh: '细节 26' },
  },
  {
    id: 'rff-detail-27',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail27.png',
    width: 99,
    height: 200,
    name: { en: 'Detail 27', zh: '细节 27' },
  },
  {
    id: 'rff-detail-28',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail28.png',
    width: 126,
    height: 202,
    name: { en: 'Detail 28', zh: '细节 28' },
  },
  {
    id: 'rff-detail-29',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail29.png',
    width: 74,
    height: 200,
    name: { en: 'Detail 29', zh: '细节 29' },
  },
  {
    id: 'rff-detail-30',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail30.png',
    width: 58,
    height: 200,
    name: { en: 'Detail 30', zh: '细节 30' },
  },
  {
    id: 'rff-detail-31',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail31.png',
    width: 198,
    height: 200,
    name: { en: 'Detail 31', zh: '细节 31' },
  },
  {
    id: 'rff-detail-32',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail32.png',
    width: 200,
    height: 200,
    name: { en: 'Detail 32', zh: '细节 32' },
  },
  {
    id: 'rff-detail-33',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail33.png',
    width: 199,
    height: 201,
    name: { en: 'Detail 33', zh: '细节 33' },
  },
  {
    id: 'rff-detail-34',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail34.png',
    width: 200,
    height: 55,
    name: { en: 'Detail 34', zh: '细节 34' },
  },
  {
    id: 'rff-detail-35',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail35.png',
    width: 63,
    height: 201,
    name: { en: 'Detail 35', zh: '细节 35' },
  },
  {
    id: 'rff-detail-36',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail36.png',
    width: 104,
    height: 200,
    name: { en: 'Detail 36', zh: '细节 36' },
  },
  {
    id: 'rff-detail-37',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail37.png',
    width: 201,
    height: 201,
    name: { en: 'Detail 37', zh: '细节 37' },
  },
  {
    id: 'rff-detail-38',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail38.png',
    width: 128,
    height: 230,
    name: { en: 'Detail 38', zh: '细节 38' },
  },
  {
    id: 'rff-detail-39',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail39.png',
    width: 202,
    height: 104,
    name: { en: 'Detail 39', zh: '细节 39' },
  },
  {
    id: 'rff-detail-40',
    category: 'detail',
    publicPath: '/emblem-creator/rollforfantasy/detail40.png',
    width: 124,
    height: 201,
    name: { en: 'Detail 40', zh: '细节 40' },
  },
  {
    id: 'rff-animal-1',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal1.png',
    width: 120,
    height: 142,
    name: { en: 'Animal 1', zh: '动物 1' },
  },
  {
    id: 'rff-animal-2',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal2.png',
    width: 134,
    height: 158,
    name: { en: 'Animal 2', zh: '动物 2' },
  },
  {
    id: 'rff-animal-3',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal3.png',
    width: 164,
    height: 113,
    name: { en: 'Animal 3', zh: '动物 3' },
  },
  {
    id: 'rff-animal-4',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal4.png',
    width: 159,
    height: 165,
    name: { en: 'Animal 4', zh: '动物 4' },
  },
  {
    id: 'rff-animal-5',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal5.png',
    width: 118,
    height: 182,
    name: { en: 'Animal 5', zh: '动物 5' },
  },
  {
    id: 'rff-animal-6',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal6.png',
    width: 140,
    height: 179,
    name: { en: 'Animal 6', zh: '动物 6' },
  },
  {
    id: 'rff-animal-7',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal7.png',
    width: 150,
    height: 165,
    name: { en: 'Animal 7', zh: '动物 7' },
  },
  {
    id: 'rff-animal-8',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal8.png',
    width: 144,
    height: 164,
    name: { en: 'Animal 8', zh: '动物 8' },
  },
  {
    id: 'rff-animal-9',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal9.png',
    width: 152,
    height: 163,
    name: { en: 'Animal 9', zh: '动物 9' },
  },
  {
    id: 'rff-animal-10',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal10.png',
    width: 153,
    height: 190,
    name: { en: 'Animal 10', zh: '动物 10' },
  },
  {
    id: 'rff-animal-11',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal11.png',
    width: 162,
    height: 82,
    name: { en: 'Animal 11', zh: '动物 11' },
  },
  {
    id: 'rff-animal-12',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal12.png',
    width: 165,
    height: 157,
    name: { en: 'Animal 12', zh: '动物 12' },
  },
  {
    id: 'rff-animal-13',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal13.png',
    width: 133,
    height: 158,
    name: { en: 'Animal 13', zh: '动物 13' },
  },
  {
    id: 'rff-animal-14',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal14.png',
    width: 167,
    height: 133,
    name: { en: 'Animal 14', zh: '动物 14' },
  },
  {
    id: 'rff-animal-15',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal15.png',
    width: 143,
    height: 167,
    name: { en: 'Animal 15', zh: '动物 15' },
  },
  {
    id: 'rff-animal-16',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal16.png',
    width: 146,
    height: 170,
    name: { en: 'Animal 16', zh: '动物 16' },
  },
  {
    id: 'rff-animal-17',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal17.png',
    width: 110,
    height: 163,
    name: { en: 'Animal 17', zh: '动物 17' },
  },
  {
    id: 'rff-animal-18',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal18.png',
    width: 166,
    height: 113,
    name: { en: 'Animal 18', zh: '动物 18' },
  },
  {
    id: 'rff-animal-19',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal19.png',
    width: 166,
    height: 116,
    name: { en: 'Animal 19', zh: '动物 19' },
  },
  {
    id: 'rff-animal-20',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal20.png',
    width: 170,
    height: 60,
    name: { en: 'Animal 20', zh: '动物 20' },
  },
  {
    id: 'rff-animal-21',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal21.png',
    width: 170,
    height: 127,
    name: { en: 'Animal 21', zh: '动物 21' },
  },
  {
    id: 'rff-animal-22',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal22.png',
    width: 161,
    height: 129,
    name: { en: 'Animal 22', zh: '动物 22' },
  },
  {
    id: 'rff-animal-23',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal23.png',
    width: 131,
    height: 140,
    name: { en: 'Animal 23', zh: '动物 23' },
  },
  {
    id: 'rff-animal-24',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal24.png',
    width: 147,
    height: 174,
    name: { en: 'Animal 24', zh: '动物 24' },
  },
  {
    id: 'rff-animal-25',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal25.png',
    width: 92,
    height: 141,
    name: { en: 'Animal 25', zh: '动物 25' },
  },
  {
    id: 'rff-animal-26',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal26.png',
    width: 125,
    height: 122,
    name: { en: 'Animal 26', zh: '动物 26' },
  },
  {
    id: 'rff-animal-27',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal27.png',
    width: 143,
    height: 169,
    name: { en: 'Animal 27', zh: '动物 27' },
  },
  {
    id: 'rff-animal-28',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal28.png',
    width: 153,
    height: 85,
    name: { en: 'Animal 28', zh: '动物 28' },
  },
  {
    id: 'rff-animal-29',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal29.png',
    width: 145,
    height: 161,
    name: { en: 'Animal 29', zh: '动物 29' },
  },
  {
    id: 'rff-animal-30',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/animal30.png',
    width: 152,
    height: 143,
    name: { en: 'Animal 30', zh: '动物 30' },
  },
  {
    id: 'rff-weapon-1',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon1.png',
    width: 148,
    height: 164,
    name: { en: 'Weapon 1', zh: '武器 1' },
  },
  {
    id: 'rff-weapon-2',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon2.png',
    width: 131,
    height: 172,
    name: { en: 'Weapon 2', zh: '武器 2' },
  },
  {
    id: 'rff-weapon-3',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon3.png',
    width: 142,
    height: 172,
    name: { en: 'Weapon 3', zh: '武器 3' },
  },
  {
    id: 'rff-weapon-4',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon4.png',
    width: 161,
    height: 113,
    name: { en: 'Weapon 4', zh: '武器 4' },
  },
  {
    id: 'rff-weapon-5',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon5.png',
    width: 69,
    height: 175,
    name: { en: 'Weapon 5', zh: '武器 5' },
  },
  {
    id: 'rff-weapon-6',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon6.png',
    width: 161,
    height: 128,
    name: { en: 'Weapon 6', zh: '武器 6' },
  },
  {
    id: 'rff-weapon-7',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon7.png',
    width: 113,
    height: 172,
    name: { en: 'Weapon 7', zh: '武器 7' },
  },
  {
    id: 'rff-weapon-8',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon8.png',
    width: 132,
    height: 128,
    name: { en: 'Weapon 8', zh: '武器 8' },
  },
  {
    id: 'rff-weapon-9',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon9.png',
    width: 135,
    height: 137,
    name: { en: 'Weapon 9', zh: '武器 9' },
  },
  {
    id: 'rff-weapon-10',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon10.png',
    width: 89,
    height: 173,
    name: { en: 'Weapon 10', zh: '武器 10' },
  },
  {
    id: 'rff-weapon-11',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon11.png',
    width: 171,
    height: 136,
    name: { en: 'Weapon 11', zh: '武器 11' },
  },
  {
    id: 'rff-weapon-12',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon12.png',
    width: 125,
    height: 163,
    name: { en: 'Weapon 12', zh: '武器 12' },
  },
  {
    id: 'rff-weapon-13',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon13.png',
    width: 164,
    height: 135,
    name: { en: 'Weapon 13', zh: '武器 13' },
  },
  {
    id: 'rff-weapon-14',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon14.png',
    width: 64,
    height: 161,
    name: { en: 'Weapon 14', zh: '武器 14' },
  },
  {
    id: 'rff-weapon-15',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon15.png',
    width: 140,
    height: 57,
    name: { en: 'Weapon 15', zh: '武器 15' },
  },
  {
    id: 'rff-weapon-16',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon16.png',
    width: 86,
    height: 168,
    name: { en: 'Weapon 16', zh: '武器 16' },
  },
  {
    id: 'rff-weapon-17',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon17.png',
    width: 161,
    height: 118,
    name: { en: 'Weapon 17', zh: '武器 17' },
  },
  {
    id: 'rff-weapon-18',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon18.png',
    width: 43,
    height: 160,
    name: { en: 'Weapon 18', zh: '武器 18' },
  },
  {
    id: 'rff-weapon-19',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon19.png',
    width: 123,
    height: 115,
    name: { en: 'Weapon 19', zh: '武器 19' },
  },
  {
    id: 'rff-weapon-20',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon20.png',
    width: 123,
    height: 160,
    name: { en: 'Weapon 20', zh: '武器 20' },
  },
  {
    id: 'rff-weapon-21',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon21.png',
    width: 31,
    height: 165,
    name: { en: 'Weapon 21', zh: '武器 21' },
  },
  {
    id: 'rff-weapon-22',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon22.png',
    width: 165,
    height: 152,
    name: { en: 'Weapon 22', zh: '武器 22' },
  },
  {
    id: 'rff-weapon-23',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon23.png',
    width: 171,
    height: 143,
    name: { en: 'Weapon 23', zh: '武器 23' },
  },
  {
    id: 'rff-weapon-24',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon24.png',
    width: 152,
    height: 139,
    name: { en: 'Weapon 24', zh: '武器 24' },
  },
  {
    id: 'rff-weapon-25',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon25.png',
    width: 137,
    height: 173,
    name: { en: 'Weapon 25', zh: '武器 25' },
  },
  {
    id: 'rff-weapon-26',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon26.png',
    width: 169,
    height: 150,
    name: { en: 'Weapon 26', zh: '武器 26' },
  },
  {
    id: 'rff-weapon-27',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/weapon27.png',
    width: 88,
    height: 167,
    name: { en: 'Weapon 27', zh: '武器 27' },
  },
  {
    id: 'rff-icon-1',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon1.png',
    width: 138,
    height: 123,
    name: { en: 'Icon 1', zh: '图标 1' },
  },
  {
    id: 'rff-icon-2',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon2.png',
    width: 100,
    height: 100,
    name: { en: 'Icon 2', zh: '图标 2' },
  },
  {
    id: 'rff-icon-3',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon3.png',
    width: 102,
    height: 102,
    name: { en: 'Icon 3', zh: '图标 3' },
  },
  {
    id: 'rff-icon-4',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon4.png',
    width: 100,
    height: 100,
    name: { en: 'Icon 4', zh: '图标 4' },
  },
  {
    id: 'rff-icon-5',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon5.png',
    width: 144,
    height: 118,
    name: { en: 'Icon 5', zh: '图标 5' },
  },
  {
    id: 'rff-icon-6',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon6.png',
    width: 144,
    height: 118,
    name: { en: 'Icon 6', zh: '图标 6' },
  },
  {
    id: 'rff-icon-7',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon7.png',
    width: 142,
    height: 141,
    name: { en: 'Icon 7', zh: '图标 7' },
  },
  {
    id: 'rff-icon-8',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon8.png',
    width: 146,
    height: 139,
    name: { en: 'Icon 8', zh: '图标 8' },
  },
  {
    id: 'rff-icon-9',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon9.png',
    width: 116,
    height: 116,
    name: { en: 'Icon 9', zh: '图标 9' },
  },
  {
    id: 'rff-icon-10',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon10.png',
    width: 50,
    height: 155,
    name: { en: 'Icon 10', zh: '图标 10' },
  },
  {
    id: 'rff-icon-11',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon11.png',
    width: 144,
    height: 143,
    name: { en: 'Icon 11', zh: '图标 11' },
  },
  {
    id: 'rff-icon-12',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon12.png',
    width: 126,
    height: 126,
    name: { en: 'Icon 12', zh: '图标 12' },
  },
  {
    id: 'rff-icon-13',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon13.png',
    width: 144,
    height: 143,
    name: { en: 'Icon 13', zh: '图标 13' },
  },
  {
    id: 'rff-icon-14',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon14.png',
    width: 122,
    height: 121,
    name: { en: 'Icon 14', zh: '图标 14' },
  },
  {
    id: 'rff-icon-15',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon15.png',
    width: 119,
    height: 155,
    name: { en: 'Icon 15', zh: '图标 15' },
  },
  {
    id: 'rff-icon-16',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon16.png',
    width: 118,
    height: 136,
    name: { en: 'Icon 16', zh: '图标 16' },
  },
  {
    id: 'rff-icon-17',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon17.png',
    width: 134,
    height: 146,
    name: { en: 'Icon 17', zh: '图标 17' },
  },
  {
    id: 'rff-icon-18',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon18.png',
    width: 142,
    height: 143,
    name: { en: 'Icon 18', zh: '图标 18' },
  },
  {
    id: 'rff-icon-19',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon19.png',
    width: 126,
    height: 143,
    name: { en: 'Icon 19', zh: '图标 19' },
  },
  {
    id: 'rff-icon-20',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon20.png',
    width: 114,
    height: 131,
    name: { en: 'Icon 20', zh: '图标 20' },
  },
  {
    id: 'rff-icon-21',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon21.png',
    width: 107,
    height: 114,
    name: { en: 'Icon 21', zh: '图标 21' },
  },
  {
    id: 'rff-icon-22',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon22.png',
    width: 128,
    height: 137,
    name: { en: 'Icon 22', zh: '图标 22' },
  },
  {
    id: 'rff-icon-23',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon23.png',
    width: 128,
    height: 82,
    name: { en: 'Icon 23', zh: '图标 23' },
  },
  {
    id: 'rff-icon-24',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon24.png',
    width: 138,
    height: 139,
    name: { en: 'Icon 24', zh: '图标 24' },
  },
  {
    id: 'rff-icon-25',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon25.png',
    width: 122,
    height: 122,
    name: { en: 'Icon 25', zh: '图标 25' },
  },
  {
    id: 'rff-icon-26',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon26.png',
    width: 88,
    height: 134,
    name: { en: 'Icon 26', zh: '图标 26' },
  },
  {
    id: 'rff-icon-27',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon27.png',
    width: 96,
    height: 137,
    name: { en: 'Icon 27', zh: '图标 27' },
  },
  {
    id: 'rff-icon-28',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon28.png',
    width: 174,
    height: 94,
    name: { en: 'Icon 28', zh: '图标 28' },
  },
  {
    id: 'rff-icon-29',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon29.png',
    width: 126,
    height: 126,
    name: { en: 'Icon 29', zh: '图标 29' },
  },
  {
    id: 'rff-icon-30',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon30.png',
    width: 126,
    height: 126,
    name: { en: 'Icon 30', zh: '图标 30' },
  },
  {
    id: 'rff-icon-31',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon31.png',
    width: 121,
    height: 119,
    name: { en: 'Icon 31', zh: '图标 31' },
  },
  {
    id: 'rff-icon-32',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon32.png',
    width: 150,
    height: 150,
    name: { en: 'Icon 32', zh: '图标 32' },
  },
  {
    id: 'rff-icon-33',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon33.png',
    width: 140,
    height: 140,
    name: { en: 'Icon 33', zh: '图标 33' },
  },
  {
    id: 'rff-icon-34',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon34.png',
    width: 140,
    height: 140,
    name: { en: 'Icon 34', zh: '图标 34' },
  },
  {
    id: 'rff-icon-35',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon35.png',
    width: 150,
    height: 150,
    name: { en: 'Icon 35', zh: '图标 35' },
  },
  {
    id: 'rff-icon-36',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon36.png',
    width: 143,
    height: 142,
    name: { en: 'Icon 36', zh: '图标 36' },
  },
  {
    id: 'rff-icon-37',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon37.png',
    width: 147,
    height: 146,
    name: { en: 'Icon 37', zh: '图标 37' },
  },
  {
    id: 'rff-icon-38',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon38.png',
    width: 151,
    height: 150,
    name: { en: 'Icon 38', zh: '图标 38' },
  },
  {
    id: 'rff-icon-39',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon39.png',
    width: 150,
    height: 149,
    name: { en: 'Icon 39', zh: '图标 39' },
  },
  {
    id: 'rff-icon-40',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/icon40.png',
    width: 153,
    height: 153,
    name: { en: 'Icon 40', zh: '图标 40' },
  },
  {
    id: 'rff-misc-1',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc1.png',
    width: 115,
    height: 137,
    name: { en: 'Misc 1', zh: '其他 1' },
  },
  {
    id: 'rff-misc-2',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc2.png',
    width: 124,
    height: 145,
    name: { en: 'Misc 2', zh: '其他 2' },
  },
  {
    id: 'rff-misc-3',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc3.png',
    width: 116,
    height: 149,
    name: { en: 'Misc 3', zh: '其他 3' },
  },
  {
    id: 'rff-misc-4',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc4.png',
    width: 120,
    height: 102,
    name: { en: 'Misc 4', zh: '其他 4' },
  },
  {
    id: 'rff-misc-5',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc5.png',
    width: 44,
    height: 134,
    name: { en: 'Misc 5', zh: '其他 5' },
  },
  {
    id: 'rff-misc-6',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc6.png',
    width: 122,
    height: 129,
    name: { en: 'Misc 6', zh: '其他 6' },
  },
  {
    id: 'rff-misc-7',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc7.png',
    width: 76,
    height: 123,
    name: { en: 'Misc 7', zh: '其他 7' },
  },
  {
    id: 'rff-misc-8',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc8.png',
    width: 150,
    height: 95,
    name: { en: 'Misc 8', zh: '其他 8' },
  },
  {
    id: 'rff-misc-9',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc9.png',
    width: 138,
    height: 73,
    name: { en: 'Misc 9', zh: '其他 9' },
  },
  {
    id: 'rff-misc-10',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc10.png',
    width: 153,
    height: 130,
    name: { en: 'Misc 10', zh: '其他 10' },
  },
  {
    id: 'rff-misc-11',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc11.png',
    width: 153,
    height: 130,
    name: { en: 'Misc 11', zh: '其他 11' },
  },
  {
    id: 'rff-misc-12',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc12.png',
    width: 153,
    height: 136,
    name: { en: 'Misc 12', zh: '其他 12' },
  },
  {
    id: 'rff-misc-13',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc13.png',
    width: 153,
    height: 136,
    name: { en: 'Misc 13', zh: '其他 13' },
  },
  {
    id: 'rff-misc-14',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc14.png',
    width: 91,
    height: 154,
    name: { en: 'Misc 14', zh: '其他 14' },
  },
  {
    id: 'rff-misc-15',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc15.png',
    width: 92,
    height: 154,
    name: { en: 'Misc 15', zh: '其他 15' },
  },
  {
    id: 'rff-misc-16',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc16.png',
    width: 100,
    height: 158,
    name: { en: 'Misc 16', zh: '其他 16' },
  },
  {
    id: 'rff-misc-17',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc17.png',
    width: 90,
    height: 155,
    name: { en: 'Misc 17', zh: '其他 17' },
  },
  {
    id: 'rff-misc-18',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc18.png',
    width: 146,
    height: 89,
    name: { en: 'Misc 18', zh: '其他 18' },
  },
  {
    id: 'rff-misc-19',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc19.png',
    width: 146,
    height: 138,
    name: { en: 'Misc 19', zh: '其他 19' },
  },
  {
    id: 'rff-misc-20',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc20.png',
    width: 104,
    height: 105,
    name: { en: 'Misc 20', zh: '其他 20' },
  },
  {
    id: 'rff-misc-21',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc21.png',
    width: 86,
    height: 119,
    name: { en: 'Misc 21', zh: '其他 21' },
  },
  {
    id: 'rff-misc-22',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc22.png',
    width: 88,
    height: 105,
    name: { en: 'Misc 22', zh: '其他 22' },
  },
  {
    id: 'rff-misc-23',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc23.png',
    width: 101,
    height: 144,
    name: { en: 'Misc 23', zh: '其他 23' },
  },
  {
    id: 'rff-misc-24',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc24.png',
    width: 26,
    height: 138,
    name: { en: 'Misc 24', zh: '其他 24' },
  },
  {
    id: 'rff-misc-25',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc25.png',
    width: 106,
    height: 127,
    name: { en: 'Misc 25', zh: '其他 25' },
  },
  {
    id: 'rff-misc-26',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc26.png',
    width: 108,
    height: 110,
    name: { en: 'Misc 26', zh: '其他 26' },
  },
  {
    id: 'rff-misc-27',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc27.png',
    width: 42,
    height: 147,
    name: { en: 'Misc 27', zh: '其他 27' },
  },
  {
    id: 'rff-misc-28',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc28.png',
    width: 63,
    height: 162,
    name: { en: 'Misc 28', zh: '其他 28' },
  },
  {
    id: 'rff-misc-29',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc29.png',
    width: 116,
    height: 143,
    name: { en: 'Misc 29', zh: '其他 29' },
  },
  {
    id: 'rff-misc-30',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc30.png',
    width: 120,
    height: 147,
    name: { en: 'Misc 30', zh: '其他 30' },
  },
  {
    id: 'rff-misc-31',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc31.png',
    width: 102,
    height: 172,
    name: { en: 'Misc 31', zh: '其他 31' },
  },
  {
    id: 'rff-misc-32',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc32.png',
    width: 172,
    height: 89,
    name: { en: 'Misc 32', zh: '其他 32' },
  },
  {
    id: 'rff-misc-33',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc33.png',
    width: 97,
    height: 170,
    name: { en: 'Misc 33', zh: '其他 33' },
  },
  {
    id: 'rff-misc-34',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc34.png',
    width: 142,
    height: 144,
    name: { en: 'Misc 34', zh: '其他 34' },
  },
  {
    id: 'rff-misc-35',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc35.png',
    width: 141,
    height: 127,
    name: { en: 'Misc 35', zh: '其他 35' },
  },
  {
    id: 'rff-misc-36',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc36.png',
    width: 158,
    height: 108,
    name: { en: 'Misc 36', zh: '其他 36' },
  },
  {
    id: 'rff-misc-37',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc37.png',
    width: 175,
    height: 110,
    name: { en: 'Misc 37', zh: '其他 37' },
  },
  {
    id: 'rff-misc-38',
    category: 'crest',
    publicPath: '/emblem-creator/rollforfantasy/misc38.png',
    width: 152,
    height: 79,
    name: { en: 'Misc 38', zh: '其他 38' },
  },
];
