import type { TarotCard } from './types';

export const TAROT_CARD_BACK_SRC = '/tarot-cards/card-back.webp';

export const TAROT_CARDS: readonly TarotCard[] = [
  {
    id: 'major-00-fool',
    arcana: 'major',
    suit: null,
    rank: 0,
    name: { en: 'The Fool', zh: '愚者' },
    imageSrc: '/tarot-cards/major-00-fool.webp',
  },
  {
    id: 'major-01-magician',
    arcana: 'major',
    suit: null,
    rank: 1,
    name: { en: 'The Magician', zh: '魔术师' },
    imageSrc: '/tarot-cards/major-01-magician.webp',
  },
  {
    id: 'major-02-high-priestess',
    arcana: 'major',
    suit: null,
    rank: 2,
    name: { en: 'The High Priestess', zh: '女祭司' },
    imageSrc: '/tarot-cards/major-02-high-priestess.webp',
  },
  {
    id: 'major-03-empress',
    arcana: 'major',
    suit: null,
    rank: 3,
    name: { en: 'The Empress', zh: '皇后' },
    imageSrc: '/tarot-cards/major-03-empress.webp',
  },
  {
    id: 'major-04-emperor',
    arcana: 'major',
    suit: null,
    rank: 4,
    name: { en: 'The Emperor', zh: '皇帝' },
    imageSrc: '/tarot-cards/major-04-emperor.webp',
  },
  {
    id: 'major-05-hierophant',
    arcana: 'major',
    suit: null,
    rank: 5,
    name: { en: 'The Hierophant', zh: '教皇' },
    imageSrc: '/tarot-cards/major-05-hierophant.webp',
  },
  {
    id: 'major-06-lovers',
    arcana: 'major',
    suit: null,
    rank: 6,
    name: { en: 'The Lovers', zh: '恋人' },
    imageSrc: '/tarot-cards/major-06-lovers.webp',
  },
  {
    id: 'major-07-chariot',
    arcana: 'major',
    suit: null,
    rank: 7,
    name: { en: 'The Chariot', zh: '战车' },
    imageSrc: '/tarot-cards/major-07-chariot.webp',
  },
  {
    id: 'major-08-strength',
    arcana: 'major',
    suit: null,
    rank: 8,
    name: { en: 'Strength', zh: '力量' },
    imageSrc: '/tarot-cards/major-08-strength.webp',
  },
  {
    id: 'major-09-hermit',
    arcana: 'major',
    suit: null,
    rank: 9,
    name: { en: 'The Hermit', zh: '隐者' },
    imageSrc: '/tarot-cards/major-09-hermit.webp',
  },
  {
    id: 'major-10-wheel-of-fortune',
    arcana: 'major',
    suit: null,
    rank: 10,
    name: { en: 'Wheel of Fortune', zh: '命运之轮' },
    imageSrc: '/tarot-cards/major-10-wheel-of-fortune.webp',
  },
  {
    id: 'major-11-justice',
    arcana: 'major',
    suit: null,
    rank: 11,
    name: { en: 'Justice', zh: '正义' },
    imageSrc: '/tarot-cards/major-11-justice.webp',
  },
  {
    id: 'major-12-hanged-man',
    arcana: 'major',
    suit: null,
    rank: 12,
    name: { en: 'The Hanged Man', zh: '倒吊人' },
    imageSrc: '/tarot-cards/major-12-hanged-man.webp',
  },
  {
    id: 'major-13-death',
    arcana: 'major',
    suit: null,
    rank: 13,
    name: { en: 'Death', zh: '死神' },
    imageSrc: '/tarot-cards/major-13-death.webp',
  },
  {
    id: 'major-14-temperance',
    arcana: 'major',
    suit: null,
    rank: 14,
    name: { en: 'Temperance', zh: '节制' },
    imageSrc: '/tarot-cards/major-14-temperance.webp',
  },
  {
    id: 'major-15-devil',
    arcana: 'major',
    suit: null,
    rank: 15,
    name: { en: 'The Devil', zh: '恶魔' },
    imageSrc: '/tarot-cards/major-15-devil.webp',
  },
  {
    id: 'major-16-tower',
    arcana: 'major',
    suit: null,
    rank: 16,
    name: { en: 'The Tower', zh: '高塔' },
    imageSrc: '/tarot-cards/major-16-tower.webp',
  },
  {
    id: 'major-17-star',
    arcana: 'major',
    suit: null,
    rank: 17,
    name: { en: 'The Star', zh: '星星' },
    imageSrc: '/tarot-cards/major-17-star.webp',
  },
  {
    id: 'major-18-moon',
    arcana: 'major',
    suit: null,
    rank: 18,
    name: { en: 'The Moon', zh: '月亮' },
    imageSrc: '/tarot-cards/major-18-moon.webp',
  },
  {
    id: 'major-19-sun',
    arcana: 'major',
    suit: null,
    rank: 19,
    name: { en: 'The Sun', zh: '太阳' },
    imageSrc: '/tarot-cards/major-19-sun.webp',
  },
  {
    id: 'major-20-judgement',
    arcana: 'major',
    suit: null,
    rank: 20,
    name: { en: 'Judgement', zh: '审判' },
    imageSrc: '/tarot-cards/major-20-judgement.webp',
  },
  {
    id: 'major-21-world',
    arcana: 'major',
    suit: null,
    rank: 21,
    name: { en: 'The World', zh: '世界' },
    imageSrc: '/tarot-cards/major-21-world.webp',
  },
  {
    id: 'cups-01',
    arcana: 'minor',
    suit: 'cups',
    rank: 1,
    name: { en: 'Ace of Cups', zh: '圣杯王牌' },
    imageSrc: '/tarot-cards/cups-01.webp',
  },
  {
    id: 'cups-02',
    arcana: 'minor',
    suit: 'cups',
    rank: 2,
    name: { en: 'Two of Cups', zh: '圣杯二' },
    imageSrc: '/tarot-cards/cups-02.webp',
  },
  {
    id: 'cups-03',
    arcana: 'minor',
    suit: 'cups',
    rank: 3,
    name: { en: 'Three of Cups', zh: '圣杯三' },
    imageSrc: '/tarot-cards/cups-03.webp',
  },
  {
    id: 'cups-04',
    arcana: 'minor',
    suit: 'cups',
    rank: 4,
    name: { en: 'Four of Cups', zh: '圣杯四' },
    imageSrc: '/tarot-cards/cups-04.webp',
  },
  {
    id: 'cups-05',
    arcana: 'minor',
    suit: 'cups',
    rank: 5,
    name: { en: 'Five of Cups', zh: '圣杯五' },
    imageSrc: '/tarot-cards/cups-05.webp',
  },
  {
    id: 'cups-06',
    arcana: 'minor',
    suit: 'cups',
    rank: 6,
    name: { en: 'Six of Cups', zh: '圣杯六' },
    imageSrc: '/tarot-cards/cups-06.webp',
  },
  {
    id: 'cups-07',
    arcana: 'minor',
    suit: 'cups',
    rank: 7,
    name: { en: 'Seven of Cups', zh: '圣杯七' },
    imageSrc: '/tarot-cards/cups-07.webp',
  },
  {
    id: 'cups-08',
    arcana: 'minor',
    suit: 'cups',
    rank: 8,
    name: { en: 'Eight of Cups', zh: '圣杯八' },
    imageSrc: '/tarot-cards/cups-08.webp',
  },
  {
    id: 'cups-09',
    arcana: 'minor',
    suit: 'cups',
    rank: 9,
    name: { en: 'Nine of Cups', zh: '圣杯九' },
    imageSrc: '/tarot-cards/cups-09.webp',
  },
  {
    id: 'cups-10',
    arcana: 'minor',
    suit: 'cups',
    rank: 10,
    name: { en: 'Ten of Cups', zh: '圣杯十' },
    imageSrc: '/tarot-cards/cups-10.webp',
  },
  {
    id: 'cups-page',
    arcana: 'minor',
    suit: 'cups',
    rank: 'page',
    name: { en: 'Page of Cups', zh: '圣杯侍从' },
    imageSrc: '/tarot-cards/cups-page.webp',
  },
  {
    id: 'cups-knight',
    arcana: 'minor',
    suit: 'cups',
    rank: 'knight',
    name: { en: 'Knight of Cups', zh: '圣杯骑士' },
    imageSrc: '/tarot-cards/cups-knight.webp',
  },
  {
    id: 'cups-queen',
    arcana: 'minor',
    suit: 'cups',
    rank: 'queen',
    name: { en: 'Queen of Cups', zh: '圣杯王后' },
    imageSrc: '/tarot-cards/cups-queen.webp',
  },
  {
    id: 'cups-king',
    arcana: 'minor',
    suit: 'cups',
    rank: 'king',
    name: { en: 'King of Cups', zh: '圣杯国王' },
    imageSrc: '/tarot-cards/cups-king.webp',
  },
  {
    id: 'pentacles-01',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 1,
    name: { en: 'Ace of Pentacles', zh: '星币王牌' },
    imageSrc: '/tarot-cards/pentacles-01.webp',
  },
  {
    id: 'pentacles-02',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 2,
    name: { en: 'Two of Pentacles', zh: '星币二' },
    imageSrc: '/tarot-cards/pentacles-02.webp',
  },
  {
    id: 'pentacles-03',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 3,
    name: { en: 'Three of Pentacles', zh: '星币三' },
    imageSrc: '/tarot-cards/pentacles-03.webp',
  },
  {
    id: 'pentacles-04',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 4,
    name: { en: 'Four of Pentacles', zh: '星币四' },
    imageSrc: '/tarot-cards/pentacles-04.webp',
  },
  {
    id: 'pentacles-05',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 5,
    name: { en: 'Five of Pentacles', zh: '星币五' },
    imageSrc: '/tarot-cards/pentacles-05.webp',
  },
  {
    id: 'pentacles-06',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 6,
    name: { en: 'Six of Pentacles', zh: '星币六' },
    imageSrc: '/tarot-cards/pentacles-06.webp',
  },
  {
    id: 'pentacles-07',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 7,
    name: { en: 'Seven of Pentacles', zh: '星币七' },
    imageSrc: '/tarot-cards/pentacles-07.webp',
  },
  {
    id: 'pentacles-08',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 8,
    name: { en: 'Eight of Pentacles', zh: '星币八' },
    imageSrc: '/tarot-cards/pentacles-08.webp',
  },
  {
    id: 'pentacles-09',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 9,
    name: { en: 'Nine of Pentacles', zh: '星币九' },
    imageSrc: '/tarot-cards/pentacles-09.webp',
  },
  {
    id: 'pentacles-10',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 10,
    name: { en: 'Ten of Pentacles', zh: '星币十' },
    imageSrc: '/tarot-cards/pentacles-10.webp',
  },
  {
    id: 'pentacles-page',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'page',
    name: { en: 'Page of Pentacles', zh: '星币侍从' },
    imageSrc: '/tarot-cards/pentacles-page.webp',
  },
  {
    id: 'pentacles-knight',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'knight',
    name: { en: 'Knight of Pentacles', zh: '星币骑士' },
    imageSrc: '/tarot-cards/pentacles-knight.webp',
  },
  {
    id: 'pentacles-queen',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'queen',
    name: { en: 'Queen of Pentacles', zh: '星币王后' },
    imageSrc: '/tarot-cards/pentacles-queen.webp',
  },
  {
    id: 'pentacles-king',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'king',
    name: { en: 'King of Pentacles', zh: '星币国王' },
    imageSrc: '/tarot-cards/pentacles-king.webp',
  },
  {
    id: 'swords-01',
    arcana: 'minor',
    suit: 'swords',
    rank: 1,
    name: { en: 'Ace of Swords', zh: '宝剑王牌' },
    imageSrc: '/tarot-cards/swords-01.webp',
  },
  {
    id: 'swords-02',
    arcana: 'minor',
    suit: 'swords',
    rank: 2,
    name: { en: 'Two of Swords', zh: '宝剑二' },
    imageSrc: '/tarot-cards/swords-02.webp',
  },
  {
    id: 'swords-03',
    arcana: 'minor',
    suit: 'swords',
    rank: 3,
    name: { en: 'Three of Swords', zh: '宝剑三' },
    imageSrc: '/tarot-cards/swords-03.webp',
  },
  {
    id: 'swords-04',
    arcana: 'minor',
    suit: 'swords',
    rank: 4,
    name: { en: 'Four of Swords', zh: '宝剑四' },
    imageSrc: '/tarot-cards/swords-04.webp',
  },
  {
    id: 'swords-05',
    arcana: 'minor',
    suit: 'swords',
    rank: 5,
    name: { en: 'Five of Swords', zh: '宝剑五' },
    imageSrc: '/tarot-cards/swords-05.webp',
  },
  {
    id: 'swords-06',
    arcana: 'minor',
    suit: 'swords',
    rank: 6,
    name: { en: 'Six of Swords', zh: '宝剑六' },
    imageSrc: '/tarot-cards/swords-06.webp',
  },
  {
    id: 'swords-07',
    arcana: 'minor',
    suit: 'swords',
    rank: 7,
    name: { en: 'Seven of Swords', zh: '宝剑七' },
    imageSrc: '/tarot-cards/swords-07.webp',
  },
  {
    id: 'swords-08',
    arcana: 'minor',
    suit: 'swords',
    rank: 8,
    name: { en: 'Eight of Swords', zh: '宝剑八' },
    imageSrc: '/tarot-cards/swords-08.webp',
  },
  {
    id: 'swords-09',
    arcana: 'minor',
    suit: 'swords',
    rank: 9,
    name: { en: 'Nine of Swords', zh: '宝剑九' },
    imageSrc: '/tarot-cards/swords-09.webp',
  },
  {
    id: 'swords-10',
    arcana: 'minor',
    suit: 'swords',
    rank: 10,
    name: { en: 'Ten of Swords', zh: '宝剑十' },
    imageSrc: '/tarot-cards/swords-10.webp',
  },
  {
    id: 'swords-page',
    arcana: 'minor',
    suit: 'swords',
    rank: 'page',
    name: { en: 'Page of Swords', zh: '宝剑侍从' },
    imageSrc: '/tarot-cards/swords-page.webp',
  },
  {
    id: 'swords-knight',
    arcana: 'minor',
    suit: 'swords',
    rank: 'knight',
    name: { en: 'Knight of Swords', zh: '宝剑骑士' },
    imageSrc: '/tarot-cards/swords-knight.webp',
  },
  {
    id: 'swords-queen',
    arcana: 'minor',
    suit: 'swords',
    rank: 'queen',
    name: { en: 'Queen of Swords', zh: '宝剑王后' },
    imageSrc: '/tarot-cards/swords-queen.webp',
  },
  {
    id: 'swords-king',
    arcana: 'minor',
    suit: 'swords',
    rank: 'king',
    name: { en: 'King of Swords', zh: '宝剑国王' },
    imageSrc: '/tarot-cards/swords-king.webp',
  },
  {
    id: 'wands-01',
    arcana: 'minor',
    suit: 'wands',
    rank: 1,
    name: { en: 'Ace of Wands', zh: '权杖王牌' },
    imageSrc: '/tarot-cards/wands-01.webp',
  },
  {
    id: 'wands-02',
    arcana: 'minor',
    suit: 'wands',
    rank: 2,
    name: { en: 'Two of Wands', zh: '权杖二' },
    imageSrc: '/tarot-cards/wands-02.webp',
  },
  {
    id: 'wands-03',
    arcana: 'minor',
    suit: 'wands',
    rank: 3,
    name: { en: 'Three of Wands', zh: '权杖三' },
    imageSrc: '/tarot-cards/wands-03.webp',
  },
  {
    id: 'wands-04',
    arcana: 'minor',
    suit: 'wands',
    rank: 4,
    name: { en: 'Four of Wands', zh: '权杖四' },
    imageSrc: '/tarot-cards/wands-04.webp',
  },
  {
    id: 'wands-05',
    arcana: 'minor',
    suit: 'wands',
    rank: 5,
    name: { en: 'Five of Wands', zh: '权杖五' },
    imageSrc: '/tarot-cards/wands-05.webp',
  },
  {
    id: 'wands-06',
    arcana: 'minor',
    suit: 'wands',
    rank: 6,
    name: { en: 'Six of Wands', zh: '权杖六' },
    imageSrc: '/tarot-cards/wands-06.webp',
  },
  {
    id: 'wands-07',
    arcana: 'minor',
    suit: 'wands',
    rank: 7,
    name: { en: 'Seven of Wands', zh: '权杖七' },
    imageSrc: '/tarot-cards/wands-07.webp',
  },
  {
    id: 'wands-08',
    arcana: 'minor',
    suit: 'wands',
    rank: 8,
    name: { en: 'Eight of Wands', zh: '权杖八' },
    imageSrc: '/tarot-cards/wands-08.webp',
  },
  {
    id: 'wands-09',
    arcana: 'minor',
    suit: 'wands',
    rank: 9,
    name: { en: 'Nine of Wands', zh: '权杖九' },
    imageSrc: '/tarot-cards/wands-09.webp',
  },
  {
    id: 'wands-10',
    arcana: 'minor',
    suit: 'wands',
    rank: 10,
    name: { en: 'Ten of Wands', zh: '权杖十' },
    imageSrc: '/tarot-cards/wands-10.webp',
  },
  {
    id: 'wands-page',
    arcana: 'minor',
    suit: 'wands',
    rank: 'page',
    name: { en: 'Page of Wands', zh: '权杖侍从' },
    imageSrc: '/tarot-cards/wands-page.webp',
  },
  {
    id: 'wands-knight',
    arcana: 'minor',
    suit: 'wands',
    rank: 'knight',
    name: { en: 'Knight of Wands', zh: '权杖骑士' },
    imageSrc: '/tarot-cards/wands-knight.webp',
  },
  {
    id: 'wands-queen',
    arcana: 'minor',
    suit: 'wands',
    rank: 'queen',
    name: { en: 'Queen of Wands', zh: '权杖王后' },
    imageSrc: '/tarot-cards/wands-queen.webp',
  },
  {
    id: 'wands-king',
    arcana: 'minor',
    suit: 'wands',
    rank: 'king',
    name: { en: 'King of Wands', zh: '权杖国王' },
    imageSrc: '/tarot-cards/wands-king.webp',
  },
];

export function getTarotCard(id: string): TarotCard {
  const card = TAROT_CARDS.find((candidate) => candidate.id === id);

  if (!card) {
    throw new Error(`Unknown tarot card id: ${JSON.stringify(id)}.`);
  }

  return card;
}
