// Generated by scripts/generate-constellation-assets.mjs. Edit the theme sources instead.
export const CONSTELLATION_THEME_NAMES = [
  {
    "index": 1,
    "slug": "dragon",
    "nameEn": "Dragon",
    "nameZh": "龙",
    "group": "creature"
  },
  {
    "index": 2,
    "slug": "phoenix",
    "nameEn": "Phoenix",
    "nameZh": "凤凰",
    "group": "creature"
  },
  {
    "index": 3,
    "slug": "stag",
    "nameEn": "Stag",
    "nameZh": "鹿",
    "group": "creature"
  },
  {
    "index": 4,
    "slug": "wolf",
    "nameEn": "Wolf",
    "nameZh": "狼",
    "group": "creature"
  },
  {
    "index": 5,
    "slug": "raven",
    "nameEn": "Raven",
    "nameZh": "渡鸦",
    "group": "creature"
  },
  {
    "index": 6,
    "slug": "serpent",
    "nameEn": "Serpent",
    "nameZh": "蛇",
    "group": "creature"
  },
  {
    "index": 7,
    "slug": "owl",
    "nameEn": "Owl",
    "nameZh": "猫头鹰",
    "group": "creature"
  },
  {
    "index": 8,
    "slug": "lion",
    "nameEn": "Lion",
    "nameZh": "狮子",
    "group": "creature"
  },
  {
    "index": 9,
    "slug": "bear",
    "nameEn": "Bear",
    "nameZh": "熊",
    "group": "creature"
  },
  {
    "index": 10,
    "slug": "horse",
    "nameEn": "Horse",
    "nameZh": "马",
    "group": "creature"
  },
  {
    "index": 11,
    "slug": "fish",
    "nameEn": "Fish",
    "nameZh": "鱼",
    "group": "creature"
  },
  {
    "index": 12,
    "slug": "whale",
    "nameEn": "Whale",
    "nameZh": "鲸",
    "group": "creature"
  },
  {
    "index": 13,
    "slug": "bat",
    "nameEn": "Bat",
    "nameZh": "蝙蝠",
    "group": "creature"
  },
  {
    "index": 14,
    "slug": "butterfly",
    "nameEn": "Butterfly",
    "nameZh": "蝴蝶",
    "group": "creature"
  },
  {
    "index": 15,
    "slug": "scorpion",
    "nameEn": "Scorpion",
    "nameZh": "蝎",
    "group": "creature"
  },
  {
    "index": 16,
    "slug": "turtle",
    "nameEn": "Turtle",
    "nameZh": "龟",
    "group": "creature"
  },
  {
    "index": 17,
    "slug": "archer",
    "nameEn": "Archer",
    "nameZh": "弓箭手",
    "group": "figure"
  },
  {
    "index": 18,
    "slug": "watcher",
    "nameEn": "Watcher",
    "nameZh": "守望者",
    "group": "figure"
  },
  {
    "index": 19,
    "slug": "voyager",
    "nameEn": "Voyager",
    "nameZh": "旅人",
    "group": "figure"
  },
  {
    "index": 20,
    "slug": "mage",
    "nameEn": "Mage",
    "nameZh": "法师",
    "group": "figure"
  },
  {
    "index": 21,
    "slug": "guardian",
    "nameEn": "Guardian",
    "nameZh": "守护者",
    "group": "figure"
  },
  {
    "index": 22,
    "slug": "dancer",
    "nameEn": "Dancer",
    "nameZh": "舞者",
    "group": "figure"
  },
  {
    "index": 23,
    "slug": "planter",
    "nameEn": "Planter",
    "nameZh": "播种者",
    "group": "figure"
  },
  {
    "index": 24,
    "slug": "reaper",
    "nameEn": "Reaper",
    "nameZh": "收割者",
    "group": "figure"
  },
  {
    "index": 25,
    "slug": "sleeper",
    "nameEn": "Sleeper",
    "nameZh": "沉睡者",
    "group": "figure"
  },
  {
    "index": 26,
    "slug": "twins",
    "nameEn": "Twins",
    "nameZh": "双子",
    "group": "figure"
  },
  {
    "index": 27,
    "slug": "sword",
    "nameEn": "Sword",
    "nameZh": "剑",
    "group": "object"
  },
  {
    "index": 28,
    "slug": "shield",
    "nameEn": "Shield",
    "nameZh": "盾",
    "group": "object"
  },
  {
    "index": 29,
    "slug": "crown",
    "nameEn": "Crown",
    "nameZh": "王冠",
    "group": "object"
  },
  {
    "index": 30,
    "slug": "chalice",
    "nameEn": "Chalice",
    "nameZh": "圣杯",
    "group": "object"
  },
  {
    "index": 31,
    "slug": "key",
    "nameEn": "Key",
    "nameZh": "钥匙",
    "group": "object"
  },
  {
    "index": 32,
    "slug": "anchor",
    "nameEn": "Anchor",
    "nameZh": "锚",
    "group": "object"
  },
  {
    "index": 33,
    "slug": "ship",
    "nameEn": "Ship",
    "nameZh": "船",
    "group": "object"
  },
  {
    "index": 34,
    "slug": "lantern",
    "nameEn": "Lantern",
    "nameZh": "提灯",
    "group": "object"
  },
  {
    "index": 35,
    "slug": "hourglass",
    "nameEn": "Hourglass",
    "nameZh": "沙漏",
    "group": "object"
  },
  {
    "index": 36,
    "slug": "staff",
    "nameEn": "Staff",
    "nameZh": "法杖",
    "group": "object"
  },
  {
    "index": 37,
    "slug": "hammer",
    "nameEn": "Hammer",
    "nameZh": "锤",
    "group": "object"
  },
  {
    "index": 38,
    "slug": "book",
    "nameEn": "Book",
    "nameZh": "书",
    "group": "object"
  },
  {
    "index": 39,
    "slug": "lyre",
    "nameEn": "Lyre",
    "nameZh": "竖琴",
    "group": "object"
  },
  {
    "index": 40,
    "slug": "scales",
    "nameEn": "Scales",
    "nameZh": "天平",
    "group": "object"
  },
  {
    "index": 41,
    "slug": "horn",
    "nameEn": "Horn",
    "nameZh": "号角",
    "group": "object"
  },
  {
    "index": 42,
    "slug": "gate",
    "nameEn": "Gate",
    "nameZh": "门",
    "group": "object"
  },
  {
    "index": 43,
    "slug": "tree",
    "nameEn": "Tree",
    "nameZh": "树",
    "group": "nature"
  },
  {
    "index": 44,
    "slug": "wheat",
    "nameEn": "Wheat",
    "nameZh": "麦穗",
    "group": "nature"
  },
  {
    "index": 45,
    "slug": "mountain",
    "nameEn": "Mountain",
    "nameZh": "山峰",
    "group": "nature"
  },
  {
    "index": 46,
    "slug": "river",
    "nameEn": "River",
    "nameZh": "河流",
    "group": "nature"
  },
  {
    "index": 47,
    "slug": "wave",
    "nameEn": "Wave",
    "nameZh": "海浪",
    "group": "nature"
  },
  {
    "index": 48,
    "slug": "leaf",
    "nameEn": "Leaf",
    "nameZh": "叶",
    "group": "nature"
  },
  {
    "index": 49,
    "slug": "flower",
    "nameEn": "Flower",
    "nameZh": "花",
    "group": "nature"
  },
  {
    "index": 50,
    "slug": "flame",
    "nameEn": "Flame",
    "nameZh": "火焰",
    "group": "nature"
  },
  {
    "index": 51,
    "slug": "sun",
    "nameEn": "Sun",
    "nameZh": "太阳",
    "group": "nature"
  },
  {
    "index": 52,
    "slug": "crescent",
    "nameEn": "Crescent",
    "nameZh": "新月",
    "group": "nature"
  },
  {
    "index": 53,
    "slug": "compass",
    "nameEn": "Compass",
    "nameZh": "罗盘",
    "group": "symbol"
  },
  {
    "index": 54,
    "slug": "eye",
    "nameEn": "Eye",
    "nameZh": "眼",
    "group": "symbol"
  },
  {
    "index": 55,
    "slug": "spiral",
    "nameEn": "Spiral",
    "nameZh": "螺旋",
    "group": "symbol"
  },
  {
    "index": 56,
    "slug": "orbit",
    "nameEn": "Orbit",
    "nameZh": "轨道",
    "group": "symbol"
  },
  {
    "index": 57,
    "slug": "eclipse",
    "nameEn": "Eclipse",
    "nameZh": "日蚀",
    "group": "symbol"
  },
  {
    "index": 58,
    "slug": "star-chain",
    "nameEn": "Star Chain",
    "nameZh": "星链",
    "group": "cluster"
  },
  {
    "index": 59,
    "slug": "forked-cluster",
    "nameEn": "Forked Cluster",
    "nameZh": "分叉星群",
    "group": "cluster"
  },
  {
    "index": 60,
    "slug": "star-arc",
    "nameEn": "Star Arc",
    "nameZh": "弧形星群",
    "group": "cluster"
  },
  {
    "index": 61,
    "slug": "scattered-cluster",
    "nameEn": "Scattered Cluster",
    "nameZh": "疏散星群",
    "group": "cluster"
  }
] as const;
