// ============================================================
// 风格预设 — 一键应用主题组合
// ============================================================
import type { StylePreset } from '@/types/editor';

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'warrior',
    name: 'warrior',
    icon: '⚔️',
    borderId: 'warrior-border-01',
    maskId: 'circle',
    borderTint: '#ffffff', // 位图边框颜色默认保持纯白以免被叠底染色
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0,
  },
  {
    id: 'mage',
    name: 'mage',
    icon: '🔮',
    borderId: 'mage-border-01',
    maskId: 'circle',
    borderTint: '#ffffff',
    borderOpacity: 1,
    overlayTint: '#1e0a3e',
    overlayOpacity: 0.15,
  },
  {
    id: 'rogue',
    name: 'rogue',
    icon: '🗡️',
    borderId: 'rogue-border-01',
    maskId: 'circle',
    borderTint: '#ffffff',
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0.1,
  },
  {
    id: 'cleric',
    name: 'cleric',
    icon: '✨',
    borderId: 'cleric-border-01',
    maskId: 'circle',
    borderTint: '#ffffff',
    borderOpacity: 1,
    overlayTint: '#f5e6c8',
    overlayOpacity: 0.08,
  },
  {
    id: 'ranger',
    name: 'ranger',
    icon: '🏹',
    borderId: 'wood',
    maskId: 'circle',
    borderTint: '#ffffff',
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0,
  },
  {
    id: 'undead',
    name: 'undead',
    icon: '💀',
    borderId: 'undead-border-01',
    maskId: 'circle',
    borderTint: '#ffffff',
    borderOpacity: 1,
    overlayTint: '#1a0a2e',
    overlayOpacity: 0.2,
  },
  {
    id: 'monster',
    name: 'monster',
    icon: '🐉',
    borderId: 'monster-border-01',
    maskId: 'circle',
    borderTint: '#ffffff',
    borderOpacity: 1,
    overlayTint: '#1a0000',
    overlayOpacity: 0.1,
  },
  {
    id: 'other',
    name: 'other',
    icon: '🔘',
    borderId: 'plain-thin-ring',
    maskId: 'circle',
    borderTint: '#b79a75',
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0,
  },
];
