// ============================================================
// 风格预设 — 一键应用主题组合
// ============================================================
import type { StylePreset } from '@/types/editor';

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'warrior',
    name: 'warrior',
    icon: '⚔️',
    borderId: 'metalbarbarian',
    maskId: 'octagon',
    borderTint: '#ffffff', // 位图边框颜色默认保持纯白以免被叠底染色
    backgroundColor: '#1a0a0a',
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0,
  },
  {
    id: 'mage',
    name: 'mage',
    icon: '🔮',
    borderId: 'blueenergy',
    maskId: 'circle',
    borderTint: '#ffffff',
    backgroundColor: '#0a0a2e',
    borderOpacity: 1,
    overlayTint: '#1e0a3e',
    overlayOpacity: 0.15,
  },
  {
    id: 'rogue',
    name: 'rogue',
    icon: '🗡️',
    borderId: 'silverspikes',
    maskId: 'hexagon',
    borderTint: '#ffffff',
    backgroundColor: '#0d0d0d',
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0.1,
  },
  {
    id: 'cleric',
    name: 'cleric',
    icon: '✨',
    borderId: 'revgold',
    maskId: 'circle',
    borderTint: '#ffffff',
    backgroundColor: '#1a1510',
    borderOpacity: 1,
    overlayTint: '#f5e6c8',
    overlayOpacity: 0.08,
  },
  {
    id: 'ranger',
    name: 'ranger',
    icon: '🏹',
    borderId: 'wood',
    maskId: 'circle',
    borderTint: '#ffffff',
    backgroundColor: '#0a1a0f',
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0,
  },
  {
    id: 'undead',
    name: 'undead',
    icon: '💀',
    borderId: 'bones',
    maskId: 'decagon',
    borderTint: '#ffffff',
    backgroundColor: '#050505',
    borderOpacity: 1,
    overlayTint: '#1a0a2e',
    overlayOpacity: 0.2,
  },
  {
    id: 'monster',
    name: 'monster',
    icon: '🐉',
    borderId: 'fire',
    maskId: 'circle',
    borderTint: '#ffffff',
    backgroundColor: '#0a1a0a',
    borderOpacity: 1,
    overlayTint: '#1a0000',
    overlayOpacity: 0.1,
  },
  {
    id: 'classic',
    name: 'classic',
    icon: '🎭',
    borderId: 'steampunk',
    maskId: 'circle',
    borderTint: '#ffffff',
    backgroundColor: '#09090b',
    borderOpacity: 1,
    overlayTint: '#000000',
    overlayOpacity: 0,
  },
];
