import type { LanguageRulePair, VocabularyItem } from '@/lib/language-generator/types';

// Source: https://rollforfantasy.com/scripts/langGen.js?fgr, cases 1..25.
// The source builds each group with the same ordered trFirst replacement chain.
export const LANGUAGE_PRESET_COUNT = 25;
export const DISPLAY_ALPHABET_SOURCES: string[] = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
];

const PRESET_REPLACEMENTS: ReadonlyArray<ReadonlyArray<LanguageRulePair>> = [
  [
    { source: "I", target: "AG" },
    { source: "oo", target: "ORU" },
    { source: "mo", target: "MOU" },
    { source: "why", target: "AB" },
    { source: "br", target: "R" },
    { source: "so", target: "RO" },
    { source: "daughter", target: "QOUAR" },
    { source: " me", target: "" },
    { source: "you", target: "DOUH" },
    { source: "ou", target: "OU" },
    { source: " no", target: "" },
    { source: "fr", target: "R" },
    { source: "am", target: "UMA" },
    { source: "bu", target: "UH" },
    { source: "str", target: "QAR" },
    { source: "tr", target: "R" },
    { source: "ma", target: "OMA" },
    { source: "pp", target: "TSA" },
    { source: "ld", target: "KAD" },
    { source: "be", target: "" },
    { source: "gl", target: "K" },
    { source: "ba", target: "GHRA" },
    { source: "cl", target: "G" },
    { source: "a", target: "A" },
    { source: "b", target: "'" },
    { source: "c", target: "G" },
    { source: "d", target: "D" },
    { source: "e", target: "A" },
    { source: "f", target: "R" },
    { source: "g", target: "G" },
    { source: "h", target: "" },
    { source: "i", target: "U" },
    { source: "k", target: "CH" },
    { source: "l", target: "K" },
    { source: "m", target: "HM" },
    { source: "n", target: "R" },
    { source: "o", target: "OU" },
    { source: "p", target: "TS" },
    { source: "r", target: "R" },
    { source: "s", target: "Q" },
    { source: "t", target: "R" },
    { source: "u", target: "UH" },
    { source: "v", target: "V" },
    { source: "w", target: "B" },
    { source: "x", target: "R" },
    { source: "y", target: "D" },
  ],
  [
    { source: "I", target: "OR" },
    { source: "sis", target: "TA" },
    { source: "bro", target: "A" },
    { source: "fat", target: "GAK" },
    { source: "mot", target: "DAK" },
    { source: "aught", target: "A" },
    { source: "son", target: "KLOU" },
    { source: "st", target: "TK" },
    { source: "ght", target: "LAK" },
    { source: "nk", target: "RX" },
    { source: "yo", target: "RA" },
    { source: "sm", target: "ID" },
    { source: "eaut", target: "OAKI" },
    { source: "kn", target: "XAR" },
    { source: "cou", target: "KAR" },
    { source: "ea", target: "ORA" },
    { source: "ch", target: "KUL" },
    { source: "wh", target: "ALI" },
    { source: "ere", target: "G" },
    { source: "ni", target: "RU" },
    { source: "gl", target: "SI" },
    { source: "sh", target: "TR" },
    { source: "pp", target: "VU" },
    { source: "no", target: "RA" },
    { source: "ell", target: "ORR" },
    { source: "a", target: "A" },
    { source: "b", target: "D" },
    { source: "c", target: "K" },
    { source: "d", target: "B" },
    { source: "e", target: "O" },
    { source: "f", target: "G" },
    { source: "g", target: "S" },
    { source: "h", target: "L" },
    { source: "i", target: "'" },
    { source: "k", target: "X" },
    { source: "l", target: "R" },
    { source: "m", target: "D" },
    { source: "n", target: "R" },
    { source: "o", target: "A" },
    { source: "p", target: "V" },
    { source: "r", target: "U" },
    { source: "s", target: "T" },
    { source: "t", target: "K" },
    { source: "u", target: "I" },
    { source: "v", target: "Q" },
    { source: "w", target: "V" },
    { source: "x", target: "Z" },
    { source: "y", target: "R" },
  ],
  [
    { source: "I", target: "OR" },
    { source: "db", target: "XA" },
    { source: "ee", target: "IRI" },
    { source: "oo", target: "OU" },
    { source: "gh", target: "CH" },
    { source: " me", target: "" },
    { source: "pl", target: "G" },
    { source: "nk", target: "SIQ" },
    { source: "you", target: "GOR" },
    { source: "no ", target: "" },
    { source: "hy", target: "HIG" },
    { source: "ter", target: "" },
    { source: "sis", target: "TOUT" },
    { source: "my", target: "CH" },
    { source: "st", target: "T" },
    { source: "ly", target: "IG" },
    { source: "uty", target: "G" },
    { source: "ld", target: "GAX" },
    { source: "pp", target: "" },
    { source: "cl", target: "G" },
    { source: "lp", target: "GIP" },
    { source: "kn", target: "QIS" },
    { source: "cou", target: "" },
    { source: "a", target: "A" },
    { source: "b", target: "D" },
    { source: "c", target: "K" },
    { source: "d", target: "X" },
    { source: "e", target: "I" },
    { source: "f", target: "C" },
    { source: "g", target: "CH" },
    { source: "h", target: "H" },
    { source: "i", target: "I" },
    { source: "k", target: "Q" },
    { source: "l", target: "G" },
    { source: "m", target: "CH" },
    { source: "n", target: "S" },
    { source: "o", target: "OU" },
    { source: "p", target: "P" },
    { source: "r", target: "R" },
    { source: "s", target: "T" },
    { source: "t", target: "T" },
    { source: "u", target: "A" },
    { source: "v", target: "S" },
    { source: "w", target: "X" },
    { source: "x", target: "" },
    { source: "y", target: "G" },
  ],
  [
    { source: "I", target: "RA" },
    { source: "ght", target: "DIHN" },
    { source: "dau", target: "" },
    { source: "nk", target: "NIR" },
    { source: "you", target: "ARO" },
    { source: "no ", target: "" },
    { source: "wh", target: "NIH" },
    { source: "br", target: "LIS" },
    { source: "fr", target: "RAS" },
    { source: "tr", target: "AS" },
    { source: "st", target: "N" },
    { source: "rk", target: "SIR" },
    { source: "lp", target: "KIP" },
    { source: "kn", target: "RON" },
    { source: "pp", target: "RL" },
    { source: "ld", target: "KID" },
    { source: "sm", target: "BR" },
    { source: "cl", target: "K" },
    { source: "a", target: "A" },
    { source: "b", target: "L" },
    { source: "c", target: "K" },
    { source: "d", target: "D" },
    { source: "e", target: "O" },
    { source: "f", target: "R" },
    { source: "g", target: "D" },
    { source: "h", target: "H" },
    { source: "i", target: "E" },
    { source: "k", target: "R" },
    { source: "l", target: "K" },
    { source: "m", target: "B" },
    { source: "n", target: "N" },
    { source: "o", target: "A" },
    { source: "p", target: "P" },
    { source: "r", target: "S" },
    { source: "s", target: "L" },
    { source: "t", target: "N" },
    { source: "u", target: "O" },
    { source: "v", target: "W" },
    { source: "w", target: "N" },
    { source: "x", target: "N" },
    { source: "y", target: "A" },
  ],
  [
    { source: "I", target: "RO" },
    { source: "db", target: "BLI" },
    { source: "ly", target: "BLI" },
    { source: "ng", target: "FRIN" },
    { source: "pl", target: "V" },
    { source: "hy", target: "HIA" },
    { source: "br", target: "L" },
    { source: "daughter", target: "ZAFRI" },
    { source: "nd", target: "B" },
    { source: "my", target: "MAN" },
    { source: "tr", target: "RAL" },
    { source: "lp", target: "SAV" },
    { source: "kn", target: "ZIF" },
    { source: "pp", target: "VY" },
    { source: "ld", target: "SRI" },
    { source: "sm", target: "ZR" },
    { source: "uty", target: "" },
    { source: "ly", target: "SNY" },
    { source: "cl", target: "S" },
    { source: "a", target: "A" },
    { source: "b", target: "L" },
    { source: "c", target: "S" },
    { source: "d", target: "B" },
    { source: "e", target: "O" },
    { source: "f", target: "F" },
    { source: "g", target: "N" },
    { source: "h", target: "H" },
    { source: "i", target: "E" },
    { source: "k", target: "Z" },
    { source: "l", target: "S" },
    { source: "m", target: "M" },
    { source: "n", target: "F" },
    { source: "o", target: "O" },
    { source: "p", target: "V" },
    { source: "r", target: "L" },
    { source: "s", target: "Z" },
    { source: "t", target: "R" },
    { source: "u", target: "I" },
    { source: "v", target: "W" },
    { source: "w", target: "" },
    { source: "x", target: "S" },
    { source: "y", target: "N" },
  ],
  [
    { source: "I", target: "ES" },
    { source: "sh", target: "AS" },
    { source: "ng", target: "L" },
    { source: "nk", target: "IM" },
    { source: "you", target: "EO" },
    { source: "br", target: "R" },
    { source: "daughter", target: "RAFOL" },
    { source: "nd", target: "MIR" },
    { source: "al", target: "AFIL" },
    { source: "rk", target: "NIM" },
    { source: "lp", target: "LIF" },
    { source: "kn", target: "M" },
    { source: "ear", target: "EYAF" },
    { source: "pp", target: "F" },
    { source: "ld", target: "LIR" },
    { source: "rg", target: "L" },
    { source: "bad", target: "RAFIR" },
    { source: "a", target: "AF" },
    { source: "b", target: "R" },
    { source: "c", target: "S" },
    { source: "d", target: "R" },
    { source: "e", target: "EY" },
    { source: "f", target: "F" },
    { source: "g", target: "L" },
    { source: "h", target: "S" },
    { source: "i", target: "O" },
    { source: "k", target: "M" },
    { source: "l", target: "L" },
    { source: "m", target: "F" },
    { source: "n", target: "M" },
    { source: "o", target: "O" },
    { source: "p", target: "F" },
    { source: "r", target: "N" },
    { source: "s", target: "S" },
    { source: "t", target: "" },
    { source: "u", target: "O" },
    { source: "v", target: "W" },
    { source: "w", target: "WA" },
    { source: "x", target: "" },
    { source: "y", target: "E" },
  ],
  [
    { source: "I", target: "U" },
    { source: "sm", target: "RAN" },
    { source: "go", target: "KRU" },
    { source: "bro", target: "FAU" },
    { source: "son", target: "RUKDAS" },
    { source: "st", target: "D" },
    { source: "ght", target: "RH" },
    { source: "SM", target: "RUN" },
    { source: "all", target: "ERUR" },
    { source: "kn", target: "K" },
    { source: "ch", target: "H" },
    { source: "wh", target: "WR" },
    { source: "pp", target: "RF" },
    { source: "end", target: "KUN" },
    { source: "db", target: "N F" },
    { source: "no", target: "KRU" },
    { source: "how", target: "WUAR" },
    { source: "tr", target: "DR" },
    { source: "pr", target: "FR" },
    { source: "weak", target: "DSOKIR" },
    { source: "a", target: "E" },
    { source: "b", target: "F" },
    { source: "c", target: "S" },
    { source: "d", target: "N" },
    { source: "e", target: "A" },
    { source: "f", target: "" },
    { source: "g", target: "R" },
    { source: "h", target: "H" },
    { source: "i", target: "AU" },
    { source: "k", target: "K" },
    { source: "l", target: "R" },
    { source: "m", target: "N" },
    { source: "n", target: "K" },
    { source: "o", target: "U" },
    { source: "p", target: "F" },
    { source: "r", target: "S" },
    { source: "s", target: "R" },
    { source: "t", target: "D" },
    { source: "u", target: "I" },
    { source: "v", target: "Y" },
    { source: "w", target: "W" },
    { source: "x", target: "R" },
    { source: "y", target: "URR" },
  ],
  [
    { source: "I", target: "ER" },
    { source: " me", target: "" },
    { source: "daughter", target: "FALI" },
    { source: "ght", target: "SIR" },
    { source: "tha", target: "RASE" },
    { source: "you", target: "EROU" },
    { source: "wh", target: "MOS" },
    { source: "br", target: "N" },
    { source: "nd", target: "LIR" },
    { source: "tr", target: "RAN" },
    { source: "st", target: "FAR" },
    { source: "rk", target: "NOM" },
    { source: "kn", target: "MOL" },
    { source: "cou", target: "" },
    { source: "sh", target: "F" },
    { source: "pp", target: "PH" },
    { source: "ld", target: "LIR" },
    { source: "sm", target: "FR" },
    { source: "eau", target: "OU" },
    { source: "a", target: "E" },
    { source: "b", target: "N" },
    { source: "c", target: "F" },
    { source: "d", target: "R" },
    { source: "e", target: "E" },
    { source: "f", target: "F" },
    { source: "g", target: "L" },
    { source: "h", target: "S" },
    { source: "i", target: "O" },
    { source: "k", target: "M" },
    { source: "l", target: "L" },
    { source: "m", target: "P" },
    { source: "n", target: "L" },
    { source: "o", target: "A" },
    { source: "p", target: "PH" },
    { source: "r", target: "N" },
    { source: "s", target: "F" },
    { source: "t", target: "T" },
    { source: "u", target: "OU" },
    { source: "v", target: "W" },
    { source: "w", target: "M" },
    { source: "x", target: "" },
    { source: "y", target: "E" },
  ],
  [
    { source: "I", target: "YE" },
    { source: "oo", target: "AE" },
    { source: "daughter", target: "FEAM" },
    { source: "ht", target: "HSH" },
    { source: " me", target: "" },
    { source: "eau", target: "eo" },
    { source: "th", target: "TAH" },
    { source: " you", target: "" },
    { source: "no ", target: "" },
    { source: "fr", target: "PAH" },
    { source: "tr", target: "TAHR" },
    { source: "kn", target: "F" },
    { source: "cou", target: "O" },
    { source: "a", target: "E" },
    { source: "b", target: "S" },
    { source: "c", target: "SH" },
    { source: "d", target: "D" },
    { source: "e", target: "AE" },
    { source: "f", target: "PH" },
    { source: "g", target: "" },
    { source: "h", target: "H" },
    { source: "i", target: "E" },
    { source: "k", target: "F" },
    { source: "l", target: "L" },
    { source: "m", target: "N" },
    { source: "n", target: "M" },
    { source: "o", target: "EA" },
    { source: "p", target: "F" },
    { source: "r", target: "HR" },
    { source: "s", target: "S" },
    { source: "t", target: "TH" },
    { source: "u", target: "O" },
    { source: "v", target: "W" },
    { source: "w", target: "L" },
    { source: "x", target: "" },
    { source: "y", target: "U" },
  ],
  [
    { source: "I", target: "UY" },
    { source: "uy", target: "NAF" },
    { source: "see", target: "RASI" },
    { source: "hy", target: "AF" },
    { source: "ood", target: "YRIV" },
    { source: "ng", target: "DIK" },
    { source: "eve", target: "OI" },
    { source: "ple", target: "VIG" },
    { source: "you", target: "FINA" },
    { source: "pr", target: "VA" },
    { source: "wh", target: "S" },
    { source: "bro", target: "YI" },
    { source: "daughter", target: "SIDA" },
    { source: "friend", target: "SAESLIJ" },
    { source: "is", target: "ARES" },
    { source: "tr", target: "AJ" },
    { source: "lp", target: "GIV" },
    { source: "pp", target: "VI" },
    { source: "old", target: "IGARIV" },
    { source: "rg", target: "JIK" },
    { source: "small", target: "JIKI" },
    { source: "ty", target: "AF" },
    { source: "gly", target: "AF" },
    { source: "cl", target: "RIG" },
    { source: "stu", target: "SLA" },
    { source: "a", target: "E" },
    { source: "b", target: "Y" },
    { source: "c", target: "R" },
    { source: "d", target: "V" },
    { source: "e", target: "I" },
    { source: "f", target: "PH" },
    { source: "g", target: "K" },
    { source: "h", target: "Y" },
    { source: "i", target: "AE" },
    { source: "k", target: "" },
    { source: "l", target: "G" },
    { source: "m", target: "R" },
    { source: "n", target: "D" },
    { source: "o", target: "I" },
    { source: "p", target: "V" },
    { source: "r", target: "A'" },
    { source: "s", target: "S" },
    { source: "t", target: "L" },
    { source: "u", target: "N" },
    { source: "v", target: "O" },
    { source: "w", target: "ST" },
    { source: "x", target: "A" },
    { source: "y", target: "F" },
  ],
  [
    { source: "I", target: "IY" },
    { source: "no", target: "YJI" },
    { source: "ng", target: "SH" },
    { source: "aught", target: "" },
    { source: "ght", target: "SH" },
    { source: "pl", target: "S" },
    { source: "tha", target: "MI" },
    { source: "wh", target: "ZR" },
    { source: "ch", target: "SIM" },
    { source: "fa", target: "H" },
    { source: "friend", target: "IRYH" },
    { source: "ra", target: "LI" },
    { source: "lp", target: "SEV" },
    { source: "see", target: "HERI" },
    { source: "hate", target: "MIHRI" },
    { source: "sha", target: "SMI" },
    { source: "happy", target: "MIRYH" },
    { source: "old", target: "ISEV" },
    { source: "sma", target: "SRI" },
    { source: "beauty", target: "VILEVI" },
    { source: "bad", target: "HIX" },
    { source: "cl", target: "S" },
    { source: "ch", target: "" },
    { source: "a", target: "HI" },
    { source: "b", target: "F" },
    { source: "c", target: "S" },
    { source: "d", target: "V" },
    { source: "e", target: "I" },
    { source: "f", target: "H" },
    { source: "g", target: "SH" },
    { source: "h", target: "M" },
    { source: "i", target: "E" },
    { source: "k", target: "" },
    { source: "l", target: "S" },
    { source: "m", target: "R" },
    { source: "n", target: "H" },
    { source: "o", target: "I" },
    { source: "p", target: "V" },
    { source: "r", target: "L" },
    { source: "s", target: "S" },
    { source: "t", target: "" },
    { source: "u", target: "E" },
    { source: "v", target: "X" },
    { source: "w", target: "Z" },
    { source: "x", target: "" },
    { source: "y", target: "YH" },
  ],
  [
    { source: "I", target: "YI" },
    { source: "oo", target: "I" },
    { source: "ng", target: "S" },
    { source: "daughter", target: "ISI" },
    { source: "ght", target: "FRIX" },
    { source: "pl", target: "QR" },
    { source: "tha", target: "XIRI" },
    { source: "no ", target: "" },
    { source: "pr", target: "QORT" },
    { source: "br", target: "" },
    { source: "fr", target: "F" },
    { source: "bu", target: "IQ" },
    { source: "rk", target: "TAC" },
    { source: "lp", target: "LQIR" },
    { source: "kn", target: "CRAS" },
    { source: "pp", target: "QR" },
    { source: "ld", target: "LIR" },
    { source: "be", target: "R" },
    { source: "be", target: "AQI" },
    { source: "a", target: "I" },
    { source: "b", target: "'Q" },
    { source: "c", target: "S" },
    { source: "d", target: "R" },
    { source: "e", target: "O" },
    { source: "f", target: "F" },
    { source: "g", target: "F" },
    { source: "h", target: "R" },
    { source: "i", target: "E" },
    { source: "k", target: "C" },
    { source: "l", target: "L" },
    { source: "m", target: "S" },
    { source: "n", target: "S" },
    { source: "o", target: "I" },
    { source: "p", target: "QR" },
    { source: "r", target: "T" },
    { source: "s", target: "" },
    { source: "t", target: "X" },
    { source: "u", target: "A" },
    { source: "v", target: "W" },
    { source: "w", target: "Z" },
    { source: "x", target: "" },
    { source: "y", target: "Y" },
  ],
  [
    { source: "I", target: "IA" },
    { source: "ll", target: "LX" },
    { source: "ht", target: "IR" },
    { source: "au", target: "I" },
    { source: "th", target: "R" },
    { source: "no ", target: "" },
    { source: "fr", target: "FAZ" },
    { source: "tr", target: "AZ" },
    { source: "lp", target: "LIQ" },
    { source: "youn", target: "AI" },
    { source: "sm", target: "ZAN" },
    { source: "gl", target: "Q" },
    { source: "ver", target: "Z" },
    { source: "a", target: "I" },
    { source: "b", target: "X" },
    { source: "c", target: "Q" },
    { source: "d", target: "B" },
    { source: "e", target: "E" },
    { source: "f", target: "F" },
    { source: "g", target: "Q" },
    { source: "h", target: "R" },
    { source: "i", target: "E" },
    { source: "k", target: "C" },
    { source: "l", target: "L" },
    { source: "m", target: "N" },
    { source: "n", target: "" },
    { source: "o", target: "A" },
    { source: "p", target: "P" },
    { source: "r", target: "Z" },
    { source: "s", target: "Z" },
    { source: "t", target: "R" },
    { source: "u", target: "I" },
    { source: "v", target: "V" },
    { source: "w", target: "B" },
    { source: "x", target: "" },
    { source: "y", target: "I" },
  ],
  [
    { source: "I", target: "Y" },
    { source: "ive", target: "YA" },
    { source: "cl", target: "Q" },
    { source: "gl", target: "AQ" },
    { source: "ll", target: "Q" },
    { source: "lc", target: "G" },
    { source: "rn", target: "T" },
    { source: "ng", target: "PIB" },
    { source: "eve", target: "YE" },
    { source: "use", target: "AXY" },
    { source: "ame", target: "OSY" },
    { source: "me", target: "SARRY" },
    { source: "an", target: "ROP" },
    { source: "you", target: "ONA" },
    { source: "how", target: "ZUNO" },
    { source: "sis", target: "TON" },
    { source: "son", target: "XONAP" },
    { source: "daughter", target: "XINA" },
    { source: "friend", target: "ATRUYT" },
    { source: "st", target: "XAR" },
    { source: "tr", target: "ROT" },
    { source: "ve", target: "YA" },
    { source: "ee", target: "AYA" },
    { source: "ap", target: "IR" },
    { source: "ld", target: "QIAK" },
    { source: "la", target: "XA" },
    { source: "a", target: "O" },
    { source: "b", target: "A" },
    { source: "c", target: "G" },
    { source: "d", target: "K" },
    { source: "e", target: "Y" },
    { source: "f", target: "H" },
    { source: "g", target: "B" },
    { source: "h", target: "U" },
    { source: "i", target: "Y" },
    { source: "k", target: "" },
    { source: "l", target: "Q" },
    { source: "m", target: "S" },
    { source: "n", target: "P" },
    { source: "o", target: "ON" },
    { source: "p", target: "A" },
    { source: "r", target: "T" },
    { source: "s", target: "X" },
    { source: "t", target: "R" },
    { source: "u", target: "D" },
    { source: "v", target: "Y" },
    { source: "w", target: "Z" },
    { source: "x", target: "O" },
    { source: "y", target: "" },
  ],
  [
    { source: "I", target: "E" },
    { source: "sis", target: "KEK" },
    { source: "bro", target: "BRU" },
    { source: "fat", target: "KOTH" },
    { source: "mot", target: "KUTH" },
    { source: "aught", target: "ROTH" },
    { source: "son", target: "DATH" },
    { source: "st", target: "TH" },
    { source: "ght", target: "ROTH" },
    { source: "nk", target: "M" },
    { source: "yo", target: "A" },
    { source: "sm", target: "KR" },
    { source: "eaut", target: "ARITH" },
    { source: "kn", target: "DR" },
    { source: "cou", target: "C" },
    { source: "ea", target: "A" },
    { source: "ch", target: "R" },
    { source: "wh", target: "VR" },
    { source: "ni", target: "ME" },
    { source: "gl", target: "SR" },
    { source: "sh", target: "KR" },
    { source: "pp", target: "V" },
    { source: "no", target: "MU" },
    { source: "ell", target: "ARR" },
    { source: "a", target: "O" },
    { source: "b", target: "B" },
    { source: "c", target: "C" },
    { source: "d", target: "D" },
    { source: "e", target: "A" },
    { source: "f", target: "K" },
    { source: "g", target: "S" },
    { source: "h", target: "R" },
    { source: "i", target: "E" },
    { source: "k", target: "D" },
    { source: "l", target: "R" },
    { source: "m", target: "K" },
    { source: "n", target: "M" },
    { source: "o", target: "U" },
    { source: "p", target: "V" },
    { source: "r", target: "R" },
    { source: "s", target: "K" },
    { source: "t", target: "TH" },
    { source: "u", target: "I" },
    { source: "v", target: "Q" },
    { source: "w", target: "V" },
    { source: "x", target: "" },
    { source: "y", target: "I" },
  ],
  [
    { source: "I", target: "RO" },
    { source: "eau", target: "OT" },
    { source: "daughter", target: "TA'RIN" },
    { source: "ght", target: "RH" },
    { source: "wh", target: "RH" },
    { source: "fr", target: "R" },
    { source: "a", target: "O" },
    { source: "b", target: "D" },
    { source: "c", target: "G" },
    { source: "d", target: "D" },
    { source: "e", target: "OU" },
    { source: "f", target: "L" },
    { source: "g", target: "Q" },
    { source: "h", target: "RH" },
    { source: "i", target: "A" },
    { source: "k", target: "Q" },
    { source: "l", target: "R" },
    { source: "m", target: "N" },
    { source: "n", target: "'N" },
    { source: "o", target: "A" },
    { source: "p", target: "B" },
    { source: "r", target: "R" },
    { source: "s", target: "T" },
    { source: "t", target: "" },
    { source: "u", target: "O" },
    { source: "v", target: "R" },
    { source: "w", target: "B" },
    { source: "x", target: "" },
    { source: "y", target: "U" },
  ],
  [
    { source: "I", target: "GLO" },
    { source: "eau", target: "O" },
    { source: "au", target: "AO" },
    { source: "ng", target: "GH" },
    { source: "you", target: "IAO" },
    { source: "son", target: "ROMSOM" },
    { source: "nk", target: "FAN" },
    { source: "ght", target: "GH" },
    { source: "pl", target: "NA" },
    { source: "pro", target: "" },
    { source: "no", target: "IYFA" },
    { source: "friend", target: "SOMAF" },
    { source: "enemy", target: "IYRSOM" },
    { source: "he/she", target: "gal/galo" },
    { source: "buy", target: "SMOCO" },
    { source: "st", target: "S" },
    { source: "rk", target: "MON" },
    { source: "cou", target: "AO" },
    { source: "pro", target: "NA" },
    { source: "small", target: "GLOR" },
    { source: "beauty", target: "GASIYO" },
    { source: "is", target: "FAS" },
    { source: "ugly", target: "GASIR" },
    { source: "a", target: "A" },
    { source: "b", target: "FA" },
    { source: "c", target: "" },
    { source: "d", target: "C" },
    { source: "e", target: "O" },
    { source: "f", target: "R" },
    { source: "g", target: "GH" },
    { source: "h", target: "" },
    { source: "i", target: "A" },
    { source: "k", target: "N" },
    { source: "l", target: "R" },
    { source: "m", target: "GL" },
    { source: "n", target: "F" },
    { source: "o", target: "A" },
    { source: "p", target: "N" },
    { source: "r", target: "M" },
    { source: "s", target: "S" },
    { source: "t", target: "S" },
    { source: "u", target: "AO" },
    { source: "v", target: "RL" },
    { source: "w", target: "L" },
    { source: "x", target: "GL" },
    { source: "y", target: "IY" },
  ],
  [
    { source: "I", target: "MO" },
    { source: "ee", target: "ALI" },
    { source: "hy", target: "OI" },
    { source: "oo", target: "O" },
    { source: "db", target: "CH " },
    { source: "ng", target: "G" },
    { source: "ght", target: "S" },
    { source: "hy", target: "O" },
    { source: "son", target: "CHASEIL" },
    { source: "my", target: "M" },
    { source: "nd", target: "M" },
    { source: "st", target: "S" },
    { source: "kn", target: "N'" },
    { source: "pp", target: "FO" },
    { source: "ly", target: "LIM" },
    { source: "a", target: "O" },
    { source: "b", target: "G" },
    { source: "c", target: "Q" },
    { source: "d", target: "CH" },
    { source: "e", target: "EI" },
    { source: "f", target: "F" },
    { source: "g", target: "G" },
    { source: "h", target: "" },
    { source: "i", target: "Y" },
    { source: "k", target: "'N" },
    { source: "l", target: "L" },
    { source: "m", target: "F" },
    { source: "n", target: "M" },
    { source: "o", target: "O" },
    { source: "p", target: "F" },
    { source: "r", target: "L" },
    { source: "s", target: "S" },
    { source: "t", target: "S" },
    { source: "u", target: "O" },
    { source: "v", target: "F" },
    { source: "w", target: "S" },
    { source: "x", target: "" },
    { source: "y", target: "M" },
  ],
  [
    { source: "I", target: "AX" },
    { source: "ll", target: "CZ" },
    { source: "oo", target: "I" },
    { source: "by", target: "RAKR" },
    { source: " me", target: "" },
    { source: "pl", target: "CZ" },
    { source: "no ", target: "" },
    { source: "ow", target: "IGRI" },
    { source: "hy", target: "AXKIR" },
    { source: "daughter", target: "ZIRA" },
    { source: "fr", target: "G" },
    { source: "my", target: "VKIR" },
    { source: "ur", target: "AKIR" },
    { source: "eal", target: "AOCZI" },
    { source: "rk", target: "WAQ" },
    { source: "ay", target: "OKIR" },
    { source: "lp", target: "CZ" },
    { source: "ppy", target: "TIR" },
    { source: "ld", target: "CZIB" },
    { source: "uty", target: "KIR" },
    { source: "ugly", target: "ACZI" },
    { source: "cl", target: "CZ" },
    { source: "a", target: "O" },
    { source: "b", target: "R" },
    { source: "c", target: "K" },
    { source: "d", target: "B" },
    { source: "e", target: "A" },
    { source: "f", target: "G" },
    { source: "g", target: "X" },
    { source: "h", target: "AX" },
    { source: "i", target: "Y" },
    { source: "k", target: "Q" },
    { source: "l", target: "CZ" },
    { source: "m", target: "V" },
    { source: "n", target: "R" },
    { source: "o", target: "I" },
    { source: "p", target: "T" },
    { source: "r", target: "W" },
    { source: "s", target: "Z" },
    { source: "t", target: "" },
    { source: "u", target: "A" },
    { source: "v", target: "R" },
    { source: "w", target: "GR" },
    { source: "x", target: "" },
    { source: "y", target: "KR" },
  ],
  [
    { source: "I", target: "E" },
    { source: "au", target: "RA" },
    { source: "me", target: "NEA" },
    { source: "ing", target: "UHR" },
    { source: "eve", target: "AHE'A" },
    { source: "night", target: "RUHS" },
    { source: "pl", target: "Z" },
    { source: "pr", target: "Z" },
    { source: "ere", target: "E'ASE" },
    { source: "son", target: "URSE'AS" },
    { source: "enemy", target: "SUIRE'AS" },
    { source: "am", target: "UNUR" },
    { source: "str", target: "SR" },
    { source: "st", target: "S" },
    { source: "bu", target: "IR" },
    { source: "tr", target: "S" },
    { source: "iv", target: "UH" },
    { source: "lp", target: "S" },
    { source: "ung", target: "IR" },
    { source: "sm", target: "RIN" },
    { source: "a", target: "U" },
    { source: "b", target: "" },
    { source: "c", target: "Z" },
    { source: "d", target: "S" },
    { source: "e", target: "E'A" },
    { source: "f", target: "" },
    { source: "g", target: "F" },
    { source: "h", target: "" },
    { source: "i", target: "UH" },
    { source: "k", target: "H" },
    { source: "l", target: "S" },
    { source: "m", target: "N" },
    { source: "n", target: "R" },
    { source: "o", target: "A" },
    { source: "p", target: "Z" },
    { source: "r", target: "S" },
    { source: "s", target: "R" },
    { source: "t", target: "S" },
    { source: "u", target: "I" },
    { source: "v", target: "H" },
    { source: "w", target: "Z" },
    { source: "x", target: "" },
    { source: "y", target: "IY" },
  ],
  [
    { source: "I", target: "ROU" },
    { source: "ng", target: "K" },
    { source: "ght", target: "KH" },
    { source: "thank", target: "GHUDIG" },
    { source: "th", target: "RAGH" },
    { source: "pr", target: "R" },
    { source: "wh", target: "GH" },
    { source: "ch", target: "Q" },
    { source: "son", target: "CUDKOUR" },
    { source: "fr", target: "R" },
    { source: "sh", target: "CH" },
    { source: "tr", target: "R" },
    { source: "kn", target: "GAD" },
    { source: "ee", target: "ORU" },
    { source: "eak", target: "ORUG" },
    { source: "sm", target: "CAB" },
    { source: "eau", target: "OURO" },
    { source: "a", target: "U" },
    { source: "b", target: "G" },
    { source: "c", target: "Q" },
    { source: "d", target: "D" },
    { source: "e", target: "OU" },
    { source: "f", target: "R" },
    { source: "g", target: "K" },
    { source: "h", target: "GH" },
    { source: "i", target: "A" },
    { source: "k", target: "G" },
    { source: "l", target: "R" },
    { source: "m", target: "B" },
    { source: "n", target: "D" },
    { source: "o", target: "U" },
    { source: "p", target: "R" },
    { source: "r", target: "R" },
    { source: "s", target: "C" },
    { source: "t", target: "R" },
    { source: "u", target: "O" },
    { source: "v", target: "V" },
    { source: "w", target: "V" },
    { source: "x", target: "R" },
    { source: "y", target: "Y" },
  ],
  [
    { source: "I", target: "AR" },
    { source: "da", target: "K" },
    { source: "no", target: "AYIK" },
    { source: "sis", target: "KLAK" },
    { source: "bro", target: "KLAD" },
    { source: "fat", target: "DUD" },
    { source: "mot", target: "NUD" },
    { source: "aught", target: "KUIKH" },
    { source: "son", target: "KUIK" },
    { source: "st", target: "K" },
    { source: "ght", target: "KH" },
    { source: "nk", target: "RK" },
    { source: "yo", target: "AVA" },
    { source: "sm", target: "KN" },
    { source: "eaut", target: "OD" },
    { source: "kn", target: "KR" },
    { source: "cou", target: "DAI" },
    { source: "ea", target: "OU" },
    { source: "ch", target: "DH" },
    { source: "wh", target: "XOH" },
    { source: "ere", target: "OLO" },
    { source: "ni", target: "RA" },
    { source: "gl", target: "KR" },
    { source: "sh", target: "KH" },
    { source: "pp", target: "RK" },
    { source: "ell", target: "OROR" },
    { source: "a", target: "U" },
    { source: "b", target: "K" },
    { source: "c", target: "D" },
    { source: "d", target: "K" },
    { source: "e", target: "O" },
    { source: "f", target: "D" },
    { source: "g", target: "K" },
    { source: "h", target: "H" },
    { source: "i", target: "A" },
    { source: "k", target: "K" },
    { source: "l", target: "R" },
    { source: "m", target: "N" },
    { source: "n", target: "R" },
    { source: "o", target: "A" },
    { source: "p", target: "K" },
    { source: "r", target: "L" },
    { source: "s", target: "K" },
    { source: "t", target: "D" },
    { source: "u", target: "I" },
    { source: "v", target: "X" },
    { source: "w", target: "X" },
    { source: "x", target: "" },
    { source: "y", target: "AV" },
  ],
  [
    { source: "I", target: "OM" },
    { source: "ng", target: "MI" },
    { source: "go", target: "JIR" },
    { source: "sis", target: "SOUS" },
    { source: "bro", target: "RI" },
    { source: "fat", target: "FUS" },
    { source: "mot", target: "MIS" },
    { source: "aught", target: "UES" },
    { source: "son", target: "SIMU" },
    { source: "st", target: "S" },
    { source: "ght", target: "JIS" },
    { source: "nk", target: "MIR" },
    { source: "yo", target: "OMI" },
    { source: "sm", target: "SR" },
    { source: "eaut", target: "UES" },
    { source: "kn", target: "RAM" },
    { source: "ch", target: "C" },
    { source: "wh", target: "WOR" },
    { source: "ere", target: "UR" },
    { source: "ni", target: "M" },
    { source: "gl", target: "JARL" },
    { source: "pp", target: "PH" },
    { source: "ie", target: "U" },
    { source: "db", target: "K L" },
    { source: "a", target: "U" },
    { source: "b", target: "L" },
    { source: "c", target: "C" },
    { source: "d", target: "K" },
    { source: "e", target: "U" },
    { source: "f", target: "F" },
    { source: "g", target: "J" },
    { source: "h", target: "H" },
    { source: "i", target: "OU" },
    { source: "k", target: "R" },
    { source: "l", target: "L" },
    { source: "m", target: "M" },
    { source: "n", target: "M" },
    { source: "o", target: "I" },
    { source: "p", target: "PH" },
    { source: "r", target: "R" },
    { source: "s", target: "S" },
    { source: "t", target: "S" },
    { source: "u", target: "E" },
    { source: "v", target: "Z" },
    { source: "w", target: "W" },
    { source: "x", target: "L" },
    { source: "y", target: "OM" },
  ],
  [
    { source: "I", target: "ASH" },
    { source: "ee", target: "AQA" },
    { source: "ng", target: "XIK" },
    { source: "nk", target: "X" },
    { source: "pl", target: "RAP" },
    { source: "pr", target: "R" },
    { source: "wh", target: "DASH" },
    { source: "br", target: "R" },
    { source: "daughter", target: "BRIX" },
    { source: "nd", target: "XIQ" },
    { source: "ll", target: "RP" },
    { source: "lp", target: "PIR" },
    { source: "kn", target: "X" },
    { source: "sh", target: "BAH" },
    { source: "pp", target: "RI" },
    { source: "ld", target: "PIQ" },
    { source: "ly", target: "POR" },
    { source: "a", target: "U" },
    { source: "b", target: "R" },
    { source: "c", target: "" },
    { source: "d", target: "Q" },
    { source: "e", target: "A" },
    { source: "f", target: "G" },
    { source: "g", target: "K" },
    { source: "h", target: "SH" },
    { source: "i", target: "A" },
    { source: "k", target: "B" },
    { source: "l", target: "P" },
    { source: "m", target: "W" },
    { source: "n", target: "X" },
    { source: "o", target: "U" },
    { source: "p", target: "R" },
    { source: "r", target: "R" },
    { source: "s", target: "B" },
    { source: "t", target: "RA" },
    { source: "u", target: "I" },
    { source: "v", target: "V" },
    { source: "w", target: "D" },
    { source: "x", target: "" },
    { source: "y", target: "R" },
  ],
  [
    { source: "I", target: "UM" },
    { source: "pl", target: "QIR" },
    { source: "bl", target: "R" },
    { source: "nd", target: "MIR" },
    { source: "kn", target: "CR" },
    { source: "pr", target: "QIR" },
    { source: "str", target: "R" },
    { source: "sm", target: "P" },
    { source: "cl", target: "Q" },
    { source: "a", target: "YA" },
    { source: "b", target: "K" },
    { source: "c", target: "Q" },
    { source: "d", target: "R" },
    { source: "e", target: "I" },
    { source: "f", target: "G" },
    { source: "g", target: "P" },
    { source: "h", target: "" },
    { source: "i", target: "A" },
    { source: "k", target: "B" },
    { source: "l", target: "R" },
    { source: "m", target: "P" },
    { source: "n", target: "M" },
    { source: "o", target: "U" },
    { source: "p", target: "Q" },
    { source: "r", target: "R" },
    { source: "s", target: "X" },
    { source: "t", target: "" },
    { source: "u", target: "A" },
    { source: "v", target: "R" },
    { source: "w", target: "G" },
    { source: "x", target: "" },
    { source: "y", target: "UM" },
  ],
];

// Preset 14 in the source contains 24 <td> nodes; its last node is an extra blank.
const PRESET_ALPHABET_TARGETS: ReadonlyArray<ReadonlyArray<string>> = [
  ["A", "'", "G", "D", "A", "R", "G", "", "U", "CH", "K", "HM", "R", "OU", "TS", "R", "Q", "R", "UH", "V", "B", "R", "D"],
  ["A", "D", "K", "B", "O", "G", "S", "L", "'", "X", "R", "D", "R", "A", "V", "U", "T", "K", "I", "Q", "V", "Z", "R"],
  ["A", "D", "K", "X", "I", "C", "CH", "H", "I", "Q", "G", "CH", "S", "OU", "P", "R", "T", "T", "A", "S", "X", "", "G"],
  ["A", "L", "K", "D", "O", "R", "D", "H", "E", "R", "K", "B", "N", "A", "P", "S", "L", "N", "O", "W", "N", "N", "A"],
  ["A", "L", "S", "B", "O", "F", "N", "H", "E", "Z", "S", "M", "F", "O", "V", "L", "Z", "R", "I", "W", "", "S", "N"],
  ["AF", "R", "S", "R", "EY", "F", "L", "S", "O", "M", "L", "F", "M", "O", "F", "N", "S", "", "O", "W", "WA", "", "E"],
  ["E", "F", "S", "N", "A", "", "R", "H", "AU", "K", "R", "N", "K", "U", "F", "S", "R", "D", "I", "Y", "W", "R", "URR"],
  ["E", "N", "F", "R", "E", "F", "L", "S", "O", "M", "L", "P", "L", "A", "PH", "N", "F", "T", "OU", "W", "M", "", "E"],
  ["E", "S", "SH", "D", "AE", "PH", "", "H", "E", "F", "L", "N", "M", "EA", "F", "HR", "S", "TH", "O", "W", "L", "", "Y"],
  ["E", "Y", "R", "V", "I", "PH", "K", "Y", "AE", "", "G", "R", "D", "I", "V", "J", "S", "L", "N", "O", "ST", "A", "F"],
  ["HI", "F", "S", "V", "I", "H", "SH", "M", "E", "", "S", "R", "H", "I", "V", "L", "S", "", "E", "X", "Z", "", "YH"],
  ["I", "'Q", "S", "R", "O", "F", "F", "R", "E", "C", "L", "S", "S", "I", "QR", "T", "", "X", "A", "W", "Z", "", "Y"],
  ["I", "X", "Q", "B", "E", "F", "Q", "R", "E", "C", "L", "N", "", "A", "P", "Z", "Z", "R", "I", "V", "B", "", "I"],
  ["O", "A", "G", "K", "Y", "H", "B", "U", "Y", "", "Q", "S", "P", "ON", "A", "N", "T", "X", "R", "D", "Y", "Z", "O"],
  ["O", "B", "C", "D", "A", "K", "S", "R", "E", "D", "R", "K", "M", "U", "V", "R", "K", "TH", "I", "Q", "V", "", "I"],
  ["O", "D", "G", "D", "OU", "L", "Q", "RH", "A", "Q", "R", "N", "'N", "A", "B", "R", "T", "", "O", "R", "B", "", "Y"],
  ["O", "FA", "", "C", "O", "R", "GH", "", "A", "N", "R", "GL", "F", "A", "N", "M", "S", "S", "AO", "RL", "L", "GL", "IY"],
  ["O", "G", "Q", "CH", "EI", "F", "G", "", "Y", "'N", "L", "F", "M", "O", "F", "L", "S", "S", "O", "F", "S", "", "M"],
  ["O", "R", "K", "B", "A", "G", "X", "AX", "Y", "Q", "CZ", "V", "R", "I", "T", "W", "Z", "", "A", "R", "GR", "", "KR"],
  ["U", "", "Z", "S", "E'A", "", "F", "", "UH", "H", "S", "N", "R", "A", "Z", "S", "R", "S", "I", "H", "Z", "", "IY"],
  ["U", "G", "Q", "D", "OU", "R", "K", "GH", "A", "G", "R", "B", "D", "U", "R", "R", "C", "R", "O", "V", "V", "R", "Y"],
  ["U", "K", "D", "K", "O", "D", "K", "H", "A", "K", "R", "N", "R", "A", "K", "L", "K", "D", "I", "X", "X", "", "AV"],
  ["U", "L", "C", "K", "U", "F", "J", "H", "OU", "R", "L", "M", "M", "I", "PH", "R", "S", "S", "E", "Z", "W", "L", "OM"],
  ["U", "R", "", "Q", "A", "G", "K", "SH", "A", "B", "P", "W", "X", "U", "R", "R", "B", "RA", "I", "V", "D", "", "R"],
  ["YA", "K", "Q", "R", "I", "G", "P", "", "A", "B", "R", "P", "M", "U", "Q", "R", "X", "", "A", "R", "G", "", "UM"],
];

function describeReceivedValue(receivedValue: unknown): string {
  if (typeof receivedValue === 'string') return JSON.stringify(receivedValue);
  if (receivedValue === undefined) return 'undefined';
  if (receivedValue === null) return 'null';
  if (typeof receivedValue === 'number' || typeof receivedValue === 'boolean' || typeof receivedValue === 'bigint') return String(receivedValue);
  return Object.prototype.toString.call(receivedValue);
}

function requirePresetId(receivedPresetId: unknown): number {
  if (typeof receivedPresetId === 'number' && Number.isInteger(receivedPresetId) && receivedPresetId >= 1 && receivedPresetId <= LANGUAGE_PRESET_COUNT) return receivedPresetId;
  throw new Error(
    `Language generator preset must be an integer from 1 to ${LANGUAGE_PRESET_COUNT}. Received ${describeReceivedValue(receivedPresetId)}.`,
  );
}

function requireVocabularyWords(receivedWords: unknown): asserts receivedWords is readonly VocabularyItem[] {
  if (!Array.isArray(receivedWords)) {
    throw new Error(`Language generator vocabulary words must be an array. Received ${describeReceivedValue(receivedWords)}.`);
  }
  for (let wordIndex = 0; wordIndex < receivedWords.length; wordIndex += 1) {
    const receivedWord = receivedWords[wordIndex];
    if (receivedWord === null || typeof receivedWord !== 'object' || Array.isArray(receivedWord)) {
      throw new Error(`Language generator vocabulary word at index ${wordIndex} must be an object. Received ${describeReceivedValue(receivedWord)}.`);
    }
    const vocabularyWord = receivedWord as Partial<VocabularyItem>;
    for (const fieldName of ['id', 'category', 'source'] as const) {
      const fieldValue = vocabularyWord[fieldName];
      if (typeof fieldValue !== 'string') {
        throw new Error(`Language generator vocabulary word at index ${wordIndex} field ${fieldName} must be a string. Received ${describeReceivedValue(fieldValue)}.`);
      }
    }
  }
}

function applyReplacementChain(sourceText: string, replacements: ReadonlyArray<LanguageRulePair>): string {
  // The page lowercases source inputs before applying uppercase replacement targets.
  let stagedText = sourceText.toLowerCase();
  for (const replacement of replacements) stagedText = stagedText.split(replacement.source).join(replacement.target);
  return stagedText.toLowerCase();
}

function createPresetAlphabet(presetId: number): LanguageRulePair[] {
  const targets = PRESET_ALPHABET_TARGETS[presetId - 1];
  if (targets === undefined || targets.length !== DISPLAY_ALPHABET_SOURCES.length) {
    throw new Error(`Language generator preset ${presetId} alphabet must contain ${DISPLAY_ALPHABET_SOURCES.length} targets. Received ${describeReceivedValue(targets)}.`);
  }
  return DISPLAY_ALPHABET_SOURCES.map((source, sourceIndex) => ({ source, target: targets[sourceIndex] }));
}

export function generatePreset(presetId: number, words: readonly VocabularyItem[]): { results: string[]; alphabet: LanguageRulePair[] } {
  const validPresetId = requirePresetId(presetId);
  requireVocabularyWords(words);
  const replacements = PRESET_REPLACEMENTS[validPresetId - 1];
  if (replacements === undefined) throw new Error(`Language generator preset ${validPresetId} has no replacement chain. Received ${describeReceivedValue(replacements)}.`);
  return {
    results: words.map((word) => applyReplacementChain(word.source, replacements)),
    alphabet: createPresetAlphabet(validPresetId),
  };
}
