import type { VocabularyItem } from '@/lib/language-generator/types';
import type { SiteLocale } from '@/lib/site-locale';

// Source: https://rollforfantasy.com/tools/language-generator.php (tt1..tt67 input values).
// The category labels describe the redesigned navigation groups; source values stay editable.
export const VOCABULARY_CATEGORIES: Array<{
  id: string;
  labels: Record<SiteLocale, string>;
}> = [
  { id: 'greetings', labels: { en: 'Greetings & courtesy', zh: '问候与礼貌' } },
  { id: 'daily-life', labels: { en: 'Question words', zh: '疑问词' } },
  { id: 'being-trade', labels: { en: 'Being & trade', zh: '是 / 交易' } },
  { id: 'common-actions', labels: { en: 'Common actions', zh: '常见动作' } },
  { id: 'family-relations', labels: { en: 'Family relations', zh: '亲属关系' } },
  { id: 'emotions-qualities', labels: { en: 'Emotions & qualities', zh: '情绪品质' } },
  { id: 'love-appearance', labels: { en: 'Love & appearance', zh: '爱与外观' } },
  { id: 'evaluation-ability', labels: { en: 'Evaluation & ability', zh: '评价能力' } },
];

export const VOCABULARY_ENTRIES: VocabularyItem[] = [
  { id: 'tt1', category: 'greetings', source: 'yes / no' },
  { id: 'tt2', category: 'greetings', source: 'hello' },
  { id: 'tt3', category: 'greetings', source: 'welcome' },
  { id: 'tt4', category: 'greetings', source: 'goodbye' },
  { id: 'tt5', category: 'greetings', source: 'good morning' },
  { id: 'tt6', category: 'greetings', source: 'good evening' },
  { id: 'tt7', category: 'greetings', source: 'good night' },
  { id: 'tt8', category: 'greetings', source: 'excuse me' },
  { id: 'tt9', category: 'greetings', source: 'please' },
  { id: 'tt10', category: 'greetings', source: 'thank you' },
  { id: 'tt11', category: 'greetings', source: 'no problem' },
  { id: 'tt12', category: 'daily-life', source: 'how' },
  { id: 'tt13', category: 'daily-life', source: 'which' },
  { id: 'tt14', category: 'daily-life', source: 'what' },
  { id: 'tt15', category: 'daily-life', source: 'where' },
  { id: 'tt16', category: 'daily-life', source: 'who' },
  { id: 'tt17', category: 'daily-life', source: 'why' },
  { id: 'tt18', category: 'daily-life', source: 'when' },
  { id: 'tt19', category: 'being-trade', source: 'i am' },
  { id: 'tt20', category: 'being-trade', source: 'you are' },
  { id: 'tt21', category: 'being-trade', source: 'he/she is' },
  { id: 'tt22', category: 'being-trade', source: 'they are' },
  { id: 'tt23', category: 'being-trade', source: 'you are' },
  { id: 'tt24', category: 'being-trade', source: 'we are' },
  { id: 'tt25', category: 'being-trade', source: 'sell' },
  { id: 'tt26', category: 'being-trade', source: 'buy' },
  { id: 'tt27', category: 'being-trade', source: 'trade' },
  { id: 'tt28', category: 'being-trade', source: 'steal' },
  { id: 'tt29', category: 'common-actions', source: 'work' },
  { id: 'tt30', category: 'common-actions', source: 'have' },
  { id: 'tt31', category: 'common-actions', source: 'give' },
  { id: 'tt32', category: 'common-actions', source: 'say' },
  { id: 'tt33', category: 'common-actions', source: 'get' },
  { id: 'tt34', category: 'common-actions', source: 'make' },
  { id: 'tt35', category: 'common-actions', source: 'help' },
  { id: 'tt36', category: 'common-actions', source: 'know' },
  { id: 'tt37', category: 'common-actions', source: 'take' },
  { id: 'tt38', category: 'common-actions', source: 'see' },
  { id: 'tt39', category: 'common-actions', source: 'hear' },
  { id: 'tt40', category: 'family-relations', source: 'father' },
  { id: 'tt41', category: 'family-relations', source: 'mother' },
  { id: 'tt42', category: 'family-relations', source: 'brother' },
  { id: 'tt43', category: 'family-relations', source: 'sister' },
  { id: 'tt44', category: 'family-relations', source: 'son' },
  { id: 'tt45', category: 'family-relations', source: 'daughter' },
  { id: 'tt46', category: 'family-relations', source: 'friend' },
  { id: 'tt47', category: 'family-relations', source: 'enemy' },
  { id: 'tt48', category: 'emotions-qualities', source: 'courage' },
  { id: 'tt49', category: 'emotions-qualities', source: 'fear' },
  { id: 'tt50', category: 'emotions-qualities', source: 'hate' },
  { id: 'tt51', category: 'emotions-qualities', source: 'anger' },
  { id: 'tt52', category: 'emotions-qualities', source: 'happy' },
  { id: 'tt53', category: 'emotions-qualities', source: 'pride' },
  { id: 'tt54', category: 'emotions-qualities', source: 'shame' },
  { id: 'tt55', category: 'love-appearance', source: 'love' },
  { id: 'tt56', category: 'love-appearance', source: 'young' },
  { id: 'tt57', category: 'love-appearance', source: 'old' },
  { id: 'tt58', category: 'love-appearance', source: 'large' },
  { id: 'tt59', category: 'love-appearance', source: 'small' },
  { id: 'tt60', category: 'love-appearance', source: 'beauty' },
  { id: 'tt61', category: 'love-appearance', source: 'ugly' },
  { id: 'tt62', category: 'evaluation-ability', source: 'good' },
  { id: 'tt63', category: 'evaluation-ability', source: 'bad' },
  { id: 'tt64', category: 'evaluation-ability', source: 'clever' },
  { id: 'tt65', category: 'evaluation-ability', source: 'stupid' },
  { id: 'tt66', category: 'evaluation-ability', source: 'strong' },
  { id: 'tt67', category: 'evaluation-ability', source: 'weak' },
];
