import type { ChargeAssetCategory, CoatAsset, TopAssetCategory } from './types';

type WebpMaterialFolder =
  | 'animals'
  | 'crowns'
  | 'humans'
  | 'mantles'
  | 'objects'
  | 'ordinaries'
  | 'other'
  | 'plants'
  | 'supporters'
  | 'symbols';

/** Static manifest for the 1,000 local WebP materials bundled under public/coat-assets/materials. */
const animals = `alligator-passant
aurochs-rampant
badger-statant
basilisk-statant
bear-rampant
beaver-statant
bison-statant
boar-passant
bull-rampant
butterfly-displayed
camel-passant
cheetah-courant
chimera-statant
civet-statant
cockatrice-statant
condor-volant
crab-statant
crane-volant
crocodile-passant
crow-displayed
dolphin-naissant
domestic-cat-sejant
donkey-passant
dove-volant
dragon-passant
duck-volant
eagle-displayed
elephant-statant
ermine-statant
fox-rampant
frog-sejant
giraffe-statant
goat-statant
goose-naissant
greyhound-courant
griffin-rampant
hare-courant
hedgehog-statant
heron-statant
hippogriff-rampant
hydra-rampant
hyena-statant
ibis-statant
jaguar-rampant
jellyfish-displayed
leopard-passant
leviathan-naissant
lion-rampant
lizard-statant
lobster-statant
lynx-statant
mandrill-sejant
manticore-rampant
mastiff-statant
mole-passant
mongoose-passant
mule-statant
narwhal-naissant
octopus-displayed
otter-passant
owl-displayed
ox-rampant
panther-rampant
parrot-perched
peacock-displayed
pelican-vulning
pheasant-statant
phoenix-rising
porcupine-statant
qilin-rampant
quail-statant
rabbit-sejant
ram-rampant
raven-displayed
rhinoceros-rampant
rooster-statant
salamander-statant
seahorse-rampant
serpent-coiled
shark-naissant
snail-passant
squid-naissant
squirrel-sejant
stag-statant
stork-statant
swan-naissant
terrier-sejant
tiger-rampant
tortoise-statant
turkey-displayed
turtle-passant
unicorn-rampant
vulture-displayed
warhorse-rearing
whale-naissant
wolf-rampant
wolfhound-rampant
wyvern-rampant
yak-passant
zebra-statant`.split('\n');
const crowns = `acorn-crown
antler-coronet
antler-crown
archducal-coronet
baronial-cap
baronial-coronet
battlement-coronet
battlement-crown
bead-crown
bohemian-crown
byzantine-crown
celtic-crown
cinquefoil-crown
circlet-crown
closed-crown
comital-coronet
consort-crown
consort-tiara
coral-crown
coronet-with-mantle
count-coronet
crosslet-crown
crown-on-helmet
crown-with-cross
crown-with-eagle
crown-with-lion
crown-with-orb
crown-with-sceptre
crown-with-stag
crown-with-sword
crown-with-wings
dragon-crown
ducal-coronet
duke-coronet
eastern-crown
eastern-tiara
eight-point-crown
feather-crown
flame-crown
fleur-de-lis-coronet
fleur-de-lis-crown
french-crown
gemmed-crown
grapevine-crown
griffin-crown
heir-apparent-coronet
heraldic-helmet-crown
horned-crown
imperial-crown
laurel-crown
lily-crown
lombard-crown
magyar-crown
marquess-coronet
marquis-coronet
moon-crown
mural-crown
naval-coronet
naval-crown
nine-point-crown
oak-crown
open-crown
orb-crown
palisade-crown
palmette-crown
papal-crown
papal-tiara
pearl-crown
phoenix-crown
phrygian-crown
prince-coronet
prince-crown
princess-crown
radiant-crown
ribbon-crown
ring-crown
rose-crown
royal-crown
samurai-crown
saxon-crown
scottish-crown
serpentine-crown
seven-point-crown
shell-crown
sovereign-crown
spanish-crown
spiked-crown
star-crown
sunburst-crown
thistle-crown
tournament-coronet
tower-crown
trefoil-crown
triple-crown
turban-crown
unicorn-crown
velvet-cap-crown
viscount-coronet
wheat-crown
winged-crown`.split('\n');
const humans = `abbess
abbot
alchemist
amazon
apothecary
archangel
architect
armoured-knight
astronomer
baron
baroness
bishop
blacksmith
captain
cardinal
carpenter
cartographer
cherub
courtier
crossbowman
crowned-king
crowned-queen
cyclops
damsel
dancer
druid
drummer
duchess
duke
dwarf
elf
emperor
empress
engineer
executioner
farmer
faun
fencer
fisherman
friar
gargoyle
genie
giant
gnome
golem
guard
halberdier
harper
healer
herald
hermit
hooded-monk
jester
judge
longbow-archer
maiden
mason
mathematician
merchant
merfolk-king
merfolk-queen
mermaid
minotaur
minstrel
mounted-rider
musketeer
naturalist
navigator
noblewoman
nun
orc
physician
pikeman
pilgrim
piper
pope
prince
princess
reaper
sailor
satyr
scholar
scribe
seraph
shield-guardian
shipwright
singer
sorceress
spearman
sphinx
spirit
standard-bearer
swordsman
trumpeter
valkyrie
winged-angel
winged-maiden
winged-warrior
witch
wizard`.split('\n');
const mantles = `amber-mantle
astrakhan-mantle
black-canopy-mantle
black-crimson-mantle
black-gold-mantle
blue-canopy-mantle
braided-mantle
brocade-mantle
burgundy-mantle
ceremonial-mantle
chain-edged-mantle
chivalric-mantle
copper-mantle
coronation-mantle
counter-vair-mantle
crimson-canopy-mantle
crimson-ermine-mantle
crosses-mantle
damask-mantle
dragons-mantle
draped-mantle
ducal-blue-mantle
ducal-mantle
eagles-mantle
ecclesiastical-mantle
emerald-mantle
ermine-canopy-mantle
ermine-draped-canopy-mantle
ermine-spot-mantle
fan-folded-mantle
feathered-gold-mantle
feathered-silver-mantle
flame-edged-mantle
flame-edged-purple-mantle
fleurs-mantle
folded-mantle
forest-green-mantle
fox-fur-mantle
fur-lined-mantle
gathered-mantle
gold-canopy-mantle
green-canopy-mantle
green-forest-mantle
griffins-mantle
half-mantle
imperial-mantle
imperial-purple-mantle
indigo-mantle
ivory-gold-mantle
jeweled-mantle
leaf-edged-green-mantle
leopard-fur-mantle
lions-mantle
lynx-fur-mantle
midnight-mantle
miniver-mantle
moon-edged-violet-mantle
pearl-edged-mantle
pewter-mantle
pointed-mantle
princely-mantle
processional-mantle
purple-canopy-mantle
rabbit-fur-mantle
red-canopy-mantle
rose-mantle
roses-mantle
royal-blue-mantle
royal-ermine-mantle
royal-sceptre-mantle
ruby-mantle
sable-mantle
sapphire-mantle
scalloped-mantle
scarlet-ermine-mantle
shoulder-mantle
silk-lined-mantle
silver-canopy-mantle
silver-mantle
snow-edged-blue-mantle
split-crimson-mantle
split-mantle
stags-mantle
star-edged-black-mantle
stars-mantle
swept-mantle
tasselled-mantle
teal-gold-mantle
tournament-lambrequin
tournament-mantle
unicorns-mantle
vair-mantle
velvet-lined-mantle
violet-silver-mantle
white-canopy-mantle
white-gold-mantle
winged-blue-mantle
winged-crimson-mantle
winged-green-mantle
winged-mantle`.split('\n');
const objects = `arrow
astrolabe
baton
battle-axe
beacon-lantern
bell
bellows
bow
brazier
bridle
broadsword
buckler
candelabrum
candle
cannon
castle-tower
cauldron
censer
ceremonial-sword
chess-knight
chess-rook
claymore
coin
compass-wheel
compass
crossbow
crozier
dagger
dice
drum
ewer
falchion
flail
gauntlet
glaive
goblet
golden-chalice
halberd
hammer
horn
horseshoe
hourglass-symbol
inkpot
keyhole
lock
longsword
loom
lyre
mace
magnifying-glass
mariner-anchor
mast
medallion
millstone
morning-star
mortar-pestle
needle
oar
open-book
orb
ornate-hourglass
ornate-key
padlock
pike
playing-card
plough
poleaxe
quill
quiver
rapier
reliquary
rudder
sabre
sailing-ship
saw
sceptre
scimitar
scroll-case
seal-ring
seal
sextant
shears
shield-boss
ship-wheel
shortsword
spear
spindle
spur
staff
stirrup
sundial
tankard
telescope
torch
treasure-chest
trident
wand
warhammer
wax-stamp
wheel`.split('\n');
const ordinaries = `annulet
bar
barrulet
barry
base-engrailed
base
bend-sinister
bend
bendlet
bendy-sinister
bendy
bezant
billet
billetty
bordure-dovetailed
bordure
braided-cord
canton-round
canton
chain-collar
checky
chequy
chevron
chevronel
chevronny
chief-indented
chief-wavy
chief
counter-vair
cross-moline
cross-potent
cross
crosslet
curved-ribbon
dancetty
double-tressure
embattled
engrailed
escalloped
fess
fillet
floral-garland
fret
fretty
fretwork
fusilly
gusset
gyron
gyronny
hurts
indented
inescutcheon-voided
inescutcheon
invected
label-five-points
label-three-points
label
laurel-swag
lozenge-pierced
lozenge
lozengy
mascle
motto-scroll
nebuly
oak-leaf-garland
orle
pale
pall-reversed
pall-wavy
pall
pallet
paly
papellony
per-bend
per-chevron
per-fess
per-pale
pile-reversed
pile-wavy
pile
plate
pomme
quarter
quarterly
raguly
riband
ribbon-knot
roundel-ringed
roundel
rustre
saltire-engrailed
saltire-voided
saltire
split-tail-ribbon
straight-banner
torteau
tressure
urdy
vair
wavy`.split('\n');
const other = `barbute-helm
bascinet-helm
castle-compartment
ceremonial-banner
ceremonial-baton
ceremonial-collar
ceremonial-drum
ceremonial-horn
ceremonial-key
ceremonial-lance
ceremonial-orb
ceremonial-sceptre
ceremonial-staff
ceremonial-torch
close-helm
cloud-compartment
crest-cushion
crest-dragon
crest-eagle
crest-feather
crest-flame
crest-gem
crest-horn
crest-lion
crest-moon
crest-pillow
crest-seat
crest-star
crest-sun
crest-wing
crown-fan
feather-fan
feather-plume
fleur-fan
floral-compartment
footstool
forest-compartment
frog-mouth-helm
grassy-compartment
great-helm
heraldic-aureole
heraldic-escutcheon
heraldic-fan
heraldic-frame
heraldic-halo
heraldic-medallion
heraldic-pennant
heraldic-plaque
heraldic-rosette
heraldic-seal
heraldic-sunburst
heraldic-torse
kettle-hat
laurel-wreath
leaf-fan
morion-helm
motto-cartouche-baroque
motto-cartouche-crown
motto-cartouche-gothic
motto-cartouche-ornate
motto-cartouche-oval
motto-cartouche-ribbon
motto-cartouche-shield
motto-cartouche-winged
motto-cartouche
motto-scroll-curled
motto-scroll-double
mountain-compartment
peacock-fan
pedestal-arch
pedestal-cloud
pedestal-column
pedestal-rock
pedestal-wave
ribbon-fan
rocky-compartment
royal-canopy
sallet-helm
sea-compartment
shield-compartment
star-fan
stone-compartment
sun-fan
throne-back
tilting-helm
torse-ermine
torse-fan
torse-feather
torse-floral
torse-jeweled
torse-laurel
torse-oak
torse-ribbon
torse-royal
torse-triple
torse-two-tone
tournament-helm
visored-helm
wave-compartment
wing-fan`.split('\n');
const plants = `acorn-cup
acorn-pair
anemone
apple-branch
ash-leaf
ash-tree
barley-sheaf
basil
bay-leaf
beech-tree
bindweed
birch-leaf
birch-tree
blackberry
bluebell
bulrush
carnation
cattail
cedar-tree
cherry-branch
chestnut-leaf
chestnut-tree
chestnut
chrysanthemum
coconut
coriander
cornucopia
crocus
cypress-tree
daffodil
daisy
damask-rose
dandelion
date-palm
fennel
fern-frond
fig-leaf
fir-tree
fleur-de-lis
foxglove
grapevine-cluster
hibiscus
holly-leaf
honeysuckle
hop-vine
hyacinth
iris
ivy-leaf
ivy-vine
jasmine
laurel-branch
lavender
lemon-branch
lily
lotus-pod
lotus
magnolia-leaf
magnolia
maple-leaf
maple-tree
marigold
mint
morning-glory
mushroom
oak-leaf
oat-sheaf
olive-tree
orange-branch
orchid
palm-frond
parsley
peach-branch
pear-branch
peony
pine-tree
pinecone
pomegranate
poppy
primrose
raspberry
red-rose
reed
rosebud
rosemary
rye-sheaf
sage
snapdragon
strawberry
sunflower
thistle-bloom
thistle-seed
thyme
tudor-rose
tulip
violet
water-lily
wheat-sheaf
white-rose
wild-rose
willow-tree`.split('\n');
const supporters = `paired-alligators
paired-angels
paired-badgers
paired-basilisks
paired-bears
paired-beavers
paired-bison
paired-bulls
paired-butterflies
paired-camels
paired-cats
paired-cheetahs
paired-chimeras
paired-civets
paired-cockatrices
paired-condors
paired-crabs
paired-cranes
paired-crocodiles
paired-crows
paired-dolphins
paired-donkeys
paired-doves
paired-dragons
paired-ducks
paired-eagles
paired-elephants
paired-ermine
paired-foxes
paired-frogs
paired-geese
paired-giraffes
paired-goats
paired-greyhounds
paired-griffins
paired-hare
paired-hedgehogs
paired-herons
paired-hippogriffs
paired-horses
paired-hydras
paired-hyenas
paired-ibises
paired-jaguars
paired-jellyfish
paired-leopards
paired-leviathans
paired-lions
paired-lizards
paired-lobsters
paired-lynxes
paired-manticores
paired-mastiffs
paired-merfolk
paired-moles
paired-mongooses
paired-monkeys
paired-mules
paired-narwhals
paired-octopuses
paired-otters
paired-oxen
paired-panthers
paired-parrots
paired-peacocks
paired-pelicans
paired-pheasants
paired-phoenixes
paired-porcupines
paired-qilins
paired-quails
paired-rabbits
paired-rams
paired-ravens
paired-rhinos
paired-roosters
paired-salamanders
paired-seahorses
paired-serpents
paired-sharks
paired-snails
paired-squids
paired-squirrels
paired-stags
paired-storks
paired-swans
paired-terriers
paired-tigers
paired-tortoises
paired-turkeys
paired-turtles
paired-unicorns-winged
paired-unicorns
paired-vultures
paired-whales
paired-wolfhounds
paired-wolves
paired-wyverns
paired-yaks
paired-zebras`.split('\n');
const symbols = `alchemical-air
alchemical-earth
alchemical-fire
alchemical-water
all-seeing-eye
anchor-cross
ankh
aquarius-symbol
aries-symbol
balance-scales
caduceus
cancer-symbol
capricorn-symbol
chalice-symbol
clasped-hands
compass-rose
crescent-moon
crescent-star
cross-anchored
cross-bottony
cross-crosslet
cross-formy
cross-moline
cross-patonce
cross-pattee
cross-potent
cross-voided
cross-with-rays
crossed-keys
crown-and-sceptre
crown-of-thorns
eclipse
eight-point-compass
eight-point-star
endless-knot
eternal-flame
eye-of-providence
five-point-star
flaming-comet
flaming-torch
fleur-cross
four-point-compass
full-moon
gemini-symbol
grail-symbol
hand-of-glory
heart-and-arrow
infinity-knot
jupiter-symbol
key-of-heaven
leo-symbol
libra-symbol
mars-symbol
mercury-symbol
moon-and-star
neptune-symbol
nine-point-star
north-node
north-star
open-book-symbol
open-hand
orb-and-cross
ouroboros-heart
ouroboros
pisces-symbol
pluto-symbol
polestar
radiant-sun
raised-fist
rod-of-asklepios
runic-knot
sacred-heart
sacred-lance
sagittarius-symbol
saturn-symbol
scorpio-symbol
seven-point-star
shaking-hands
ship-wheel-symbol
shooting-star
six-point-star
solar-cross
solar-disc
south-node
sun-and-moon
sunburst-face
sword-and-scales
taurus-symbol
three-pronged-trident
triquetra-knot
triskelion
twelve-point-star
uranus-symbol
venus-symbol
victory-wreath
virgo-symbol
waning-moon
waxing-moon
wheel-of-fortune
winged-serpent`.split('\n');


export const webpMaterialAssets: readonly CoatAsset[] = [
  ...createChargeMaterials('animals', 'animal', animals),
  ...createChargeMaterials('objects', 'object', objects),
  ...createChargeMaterials('plants', 'plant', plants),
  ...createChargeMaterials('humans', 'human', humans),
  ...createChargeMaterials('symbols', 'symbol', symbols),
  ...createOrdinaryMaterials(ordinaries),
  ...createTopMaterials('crowns', 'crown', crowns),
  ...createTopMaterials('mantles', 'mantle', mantles),
  ...createTopMaterials('supporters', 'supporter', supporters),
  ...createTopMaterials('other', 'other', other),
];

function createChargeMaterials(
  folder: WebpMaterialFolder,
  category: ChargeAssetCategory,
  fileStems: readonly string[],
): readonly CoatAsset[] {
  assertMaterialFileStems(folder, fileStems);
  return fileStems.map((fileStem) => ({
    id: `material-${category}-${fileStem}`,
    kind: 'charge',
    category,
    name: createMaterialName(fileStem),
    searchTerms: fileStem.split('-'),
    rasterSrc: createMaterialSource(folder, fileStem),
  }));
}

function createOrdinaryMaterials(fileStems: readonly string[]): readonly CoatAsset[] {
  const folder = 'ordinaries';
  assertMaterialFileStems(folder, fileStems);
  return fileStems.map((fileStem) => ({
    id: `material-ordinary-${fileStem}`,
    kind: 'ordinary',
    name: createMaterialName(fileStem),
    searchTerms: fileStem.split('-'),
    rasterSrc: createMaterialSource(folder, fileStem),
  }));
}

function createTopMaterials(
  folder: WebpMaterialFolder,
  category: TopAssetCategory,
  fileStems: readonly string[],
): readonly CoatAsset[] {
  assertMaterialFileStems(folder, fileStems);
  return fileStems.map((fileStem) => ({
    id: `material-${category}-${fileStem}`,
    kind: 'top',
    category,
    name: createMaterialName(fileStem),
    searchTerms: fileStem.split('-'),
    rasterSrc: createMaterialSource(folder, fileStem),
  }));
}

function createMaterialName(fileStem: string) {
  const title = fileStem
    .split('-')
    .map((word) => `${word.slice(0, 1).toUpperCase()}${word.slice(1)}`)
    .join(' ');
  return { en: title, zh: title };
}

function createMaterialSource(folder: WebpMaterialFolder, fileStem: string): string {
  return `/coat-assets/materials/${folder}/${fileStem}.webp`;
}

function assertMaterialFileStems(folder: string, fileStems: readonly string[]): void {
  if (fileStems.length !== 100) {
    throw new Error(`Expected 100 WebP materials for ${folder}; received ${fileStems.length}`);
  }
  for (const fileStem of fileStems) {
    if (!/^[a-z0-9-]+$/.test(fileStem)) {
      throw new Error(`Invalid WebP material file stem for ${folder}: ${fileStem}`);
    }
  }
}

